/**
 * The generated views file: `architecture/subsystems.likec4`, one LikeC4 view
 * per subsystem enumerating the services beneath it. GENERATED, never
 * authored — authored bytes stay authored (archive's verbatim-splice promise),
 * so the tree is mirrored into a file of its own that `loam subsystem sync`
 * owns outright, and staleness against the tree is a byte compare
 * (`subsystem.views-stale` in `validate --all`), never a parse: a spike
 * confirmed a views-only document does NOT parse standalone (its `include`
 * lines reference elements the landscape defines), so nothing in loam ever
 * loads this file (and rule 26 does not change that: this file is GENERATED and
 * holds STATIC views, whose contents loam may not read in any document) — only
 * the LikeC4 renderer, which merges the whole `architecture/` project per
 * likec4.config.json, resolves it.
 *
 * Each view opens with the LABEL a human reads — `title`, and `description`
 * when the marker carries one — because this file exists only to be rendered
 * and an unlabelled view is shown by its id, which is hex-escaped for
 * injectivity and reads as `subsystem_api__rest_2dapi_2dv2_2dservices`. Both
 * strings are somebody else's words and go through `likec4String`, which
 * records what a raw one does.
 *
 * The output is deterministic and line-oriented, and both halves are the
 * contract: subsystems sorted by path, members sorted by id, ONE `include`
 * per line — so two concurrent moves into different groups touch different
 * lines and git merges the file without intervention, exactly as the
 * service-grouped landscape splice already achieves. Byte-reproducible on any
 * machine: no timestamps, no absolute paths, no readdir-order dependence (the
 * walk sorts, and every list is re-sorted here). Plain lexicographic sorts on
 * purpose — the ids' own grammar is ASCII, an INVALID name is still ordered
 * deterministically, and `compareIds`' numeric tokenizing lives in `repo/`,
 * which this package must not import (`walk.ts` says why the edge only points
 * the other way).
 *
 * Membership is TRANSITIVE: a subsystem's view includes every service beneath
 * it at any depth, so a parent's view is the whole group's map rather than an
 * empty frame around its children. An empty view body is legal LikeC4 (same
 * spike), so an empty subsystem renders as one — `subsystem new` must be
 * usable before anything moves in.
 *
 * Include lines name the landscape ELEMENT id, resolved through the same
 * element→service join `validate` uses (`serviceResolver`: explicit
 * `metadata { service }` binding first, then a title naming a real service) —
 * because element ids in real landscapes are not service ids, and a view of
 * raw service ids would silently render empty for every such fleet. A member
 * with no landscape element is omitted from the includes: the omission is
 * already an error (`landscape.service-unmodelled`), and rendering only what
 * the committed landscape resolves keeps the output a function of committed
 * bytes alone.
 */
import { type Elem } from "../../../c4/likec4.js";
import { renderContext, viewBody } from "./body.js";
import { likec4String, viewTitle } from "./text.js";
import type { FleetTree, SubsystemEntry } from "../walk.js";

/**
 * The header every generated file opens with — stable bytes, part of the
 * byte-compare contract, naming the regenerator so a reader who found the
 * file first knows what owns it.
 */
const HEADER =
  "// generated by loam — the subsystem tree under services/, one view per subsystem.\n" +
  "// Do not edit: `loam subsystem sync` regenerates this file from the directories,\n" +
  "// and `loam validate --all` reports `subsystem.views-stale` when it drifts.\n" +
  "// A scoping aid, not the fleet's architecture: author your own diagrams elsewhere.\n";

/**
 * Render the views file for a walked tree, or null when the tree has no
 * subsystems — the file must then be ABSENT, so a flat fleet never carries a
 * generated artifact that says nothing.
 */
export function renderSubsystemViews(tree: FleetTree, elements: Elem[]): string | null {
  if (tree.subsystems.length === 0) return null;
  const ctx = renderContext(tree, elements);
  const lines: string[] = [HEADER, "views {"];
  const subsystems = [...tree.subsystems].sort((a, b) => (pathKey(a) < pathKey(b) ? -1 : 1));
  for (const [i, sub] of subsystems.entries()) {
    if (i > 0) lines.push("");
    lines.push(`  // services/${pathKey(sub)}`);
    const body = viewBody(ctx, sub);
    if (body.disclosure !== null) lines.push(`  // ${body.disclosure}`);
    lines.push(`  view ${subsystemViewId(sub)} {`);
    // Metadata FIRST, and that ordering is a hard constraint rather than a
    // taste: measured, an `include` OR a `group { … }` line followed by
    // `title` is a parse error ("Expecting token of type '}' but found
    // `title`"), and one parse error in this file blanks the whole
    // `architecture/` project in the renderer.
    lines.push(`    title '${viewTitle(sub)}'`);
    const description = likec4String(sub.meta.description ?? "");
    if (description !== "") lines.push(`    description '${description}'`);
    lines.push(...body.lines);
    lines.push("  }");
  }
  lines.push("}");
  return lines.join("\n") + "\n";
}

/** The sort key and the comment spelling: the subsystem's path from services/, joined. */
function pathKey(sub: SubsystemEntry): string {
  return sub.path.join("/");
}

/**
 * A LikeC4 identifier for the view, derived from the subsystem's path so
 * nesting reads in the name — and INJECTIVE over every path the name grammar
 * admits, because the renderer refuses the whole `architecture/` project over
 * a duplicate view id. The naive folding (every non-identifier byte and the
 * join separator alike becoming `_`) collided three DISTINCT healthy names
 * onto one identifier — `a_b`, and `b` under `a`, both rendered
 * `subsystem_a_b` — so `validate --all` was green while the renderer refused
 * the fleet map; `subsystem.name-collision` never fires because the flat
 * namespace really is intact. Hence the encoding: an identifier byte
 * (`[A-Za-z0-9]`) passes through, any other byte becomes `_` + two lowercase
 * hex digits (`.` → `_2e`, `-` → `_2d`, `_` itself → `_5f` — the underscore
 * must be escaped precisely because it is BOTH legal in a name and the
 * separator), and segments join on `__`. Underscore runs then decode
 * uniquely — one is an escape, two a separator, three a separator followed
 * by an escape — so no two distinct legal paths share an identifier. A name
 * `subsystem.name-invalid` already flagged may hold a code point above 0xff
 * whose longer hex could in principle re-collide; it is deterministic still,
 * and that directory is already an error finding by name.
 *
 * EXPORTED, with its prefix, because `subsystem.view-id-collision` has to ask
 * the generator what it mints rather than re-deriving it. A check carrying its
 * own copy of the escaping above would go quiet the day the encoding changed,
 * and going quiet is the failure this whole family exists to prevent.
 */
export const SUBSYSTEM_VIEW_PREFIX = "subsystem_";

export function subsystemViewId(sub: SubsystemEntry): string {
  const segment = (name: string): string =>
    [...name].map((ch) => (/[A-Za-z0-9]/.test(ch) ? ch : `_${ch.codePointAt(0)!.toString(16).padStart(2, "0")}`)).join("");
  return `subsystem_${sub.path.map(segment).join("__")}`;
}

/**
 * Does the file on disk already SAY what `renderSubsystemViews` renders?
 *
 * The generator above only ever emits LF. `core.autocrlf=true` is Git for
 * Windows' installer default and a docs repo ships no `.gitattributes`, so an
 * ordinary Windows clone hands the file back with CRLF and not one fact
 * changed. Four call sites asked this question with a byte equality and all
 * four answered "stale" on such a clone: `loam validate` reported an error,
 * `loam subsystem sync` reported `updated` and rewrote with LF, git then showed
 * the file permanently modified, and the next checkout restored the CRLF. That
 * is a loop rather than a diagnosis, which is why the comparison lives here
 * now — the module that mints the bytes is the one that owes an answer about
 * them, and three near-copies of this rule would go stale one at a time.
 *
 * Still never a parse: a views-only document does not parse standalone, and no
 * check anywhere reads this file's content. The narrowing is from BYTES to
 * CONTENT, which is what `subsystem.views-stale`'s own message ("does not match
 * the tree") already claims. The symmetric cost is accepted and is the one
 * `core/verify/pins/pin.ts` documents for `pinnedDigest`: a pure line-ending
 * change is invisible, correctly, because it is not a change to what the file
 * says.
 *
 * `null` is carried through as itself rather than collapsing into `""`: absent,
 * must-be-absent and present-but-different are three distinct states with three
 * distinct messages, and a fleet whose views file does not exist is not a fleet
 * whose views file is blank.
 */
export function viewsAgree(actual: string | null, expected: string | null): boolean {
  const lf = (text: string | null): string | null => (text === null ? null : text.replace(/\r\n|\r/g, "\n"));
  return lf(actual) === lf(expected);
}
