/**
 * The generated subsystem views file, end to end: `loam subsystem sync`
 * renders `architecture/subsystems.likec4` deterministically from the tree,
 * and `validate --all` grades staleness as exactly ONE error on exactly one
 * file, by byte comparison — never by parsing.
 *
 * The two properties worth naming are exit criteria of the roadmap item:
 * byte-reproducibility (no timestamps, no absolute paths, no readdir-order
 * dependence — the file renders identically on any machine from the same
 * committed bytes) and line-orientation (one `include` per line, subsystems
 * sorted by path, members by id — so two concurrent moves into different
 * groups touch different lines and git merges the generated file without
 * intervention).
 */
import { describe, expect, it } from "vitest";
import { rm } from "node:fs/promises";
import { join } from "node:path";
import { LikeC4 } from "likec4";
import {
  coherentFixture,
  LANDSCAPE,
  makeProject,
  runLoam,
  treeHashes,
} from "./helpers/harness.js";

interface JsonFinding {
  severity: string;
  code: string;
  message: string;
  subject?: string;
  locations?: Array<{ path: string; role: string }>;
}

function subsystemFindings(stdout: string): JsonFinding[] {
  const payload = JSON.parse(stdout) as { targets: Array<{ findings: JsonFinding[] }> };
  return payload.targets.flatMap((t) => t.findings).filter((f) => f.code.startsWith("subsystem."));
}

/** `coherentFixture()` with payment-service filed into a marked subsystem. */
function nestedFixture(): Record<string, string> {
  const files: Record<string, string> = {};
  for (const [path, content] of Object.entries(coherentFixture())) {
    files[path.replace(/^services\/payment-service\//, "services/payments/payment-service/")] = content;
  }
  files["services/payments/subsystem.yaml"] = "title: Payments\n";
  return files;
}

const VIEWS = "architecture/subsystems.likec4";

describe("loam subsystem sync — the renderer", () => {
  it("writes one view per subsystem, sorted by path, one include per line, members resolved to landscape ELEMENT ids", async () => {
    // Two subsystems out of path order on disk plus an unfiled service; the
    // landscape names elements whose ids differ from the service ids (the
    // harness LANDSCAPE joins by TITLE), which is exactly why includes must go
    // through the element→service join rather than spelling service ids.
    const files = nestedFixture();
    files["services/web/subsystem.yaml"] = "";
    files["services/web/checkout-web/spec.md"] = "---\nservice: checkout-web\nstatus: draft\n---\n\n# checkout-web\n";
    const p = await makeProject(files);
    try {
      const res = await runLoam(p.workDir, "subsystem", "sync", "--json");
      expect(res.code).toBe(0);
      const payload = JSON.parse(res.stdout);
      expect(payload.ok).toBe(true);
      expect(payload.path).toBe(VIEWS);
      expect(payload.action).toBe("created");
      expect(payload.subsystems).toBe(2);
      // The exact bytes are the contract: deterministic, line-oriented, no
      // timestamps, no absolute paths. Pinning them whole is what makes any
      // accidental format drift loud.
      expect(await p.read(VIEWS)).toBe(
        "// generated by loam — the subsystem tree under services/, one view per subsystem.\n" +
          "// Do not edit: `loam subsystem sync` regenerates this file from the directories,\n" +
          "// and `loam validate --all` reports `subsystem.views-stale` when it drifts.\n" +
          "// A scoping aid, not the fleet's architecture: author your own diagrams elsewhere.\n" +
          "\n" +
          "views {\n" +
          "  // services/payments\n" +
          "  view subsystem_payments {\n" +
          "    title 'Payments'\n" +
          "    group 'Payments' {\n" +
          "      include paymentService\n" +
          "    }\n" +
          "  }\n" +
          "\n" +
          "  // services/web\n" +
          "  view subsystem_web {\n" +
          "    title 'web'\n" +
          "    group 'web' {\n" +
          "      include checkoutWeb\n" +
          "    }\n" +
          "  }\n" +
          "}\n",
      );
    } finally {
      await p.destroy();
    }
  });

  it("is byte-reproducible: the same logical tree written in a different order renders identical bytes", async () => {
    const forward = nestedFixture();
    forward["services/web/subsystem.yaml"] = "";
    forward["services/web/checkout-web/spec.md"] = "---\nservice: checkout-web\n---\n\n# checkout-web\n";
    const backward: Record<string, string> = {};
    for (const key of Object.keys(forward).reverse()) backward[key] = forward[key]!;
    const a = await makeProject(forward);
    const b = await makeProject(backward);
    try {
      expect((await runLoam(a.workDir, "subsystem", "sync")).code).toBe(0);
      expect((await runLoam(b.workDir, "subsystem", "sync")).code).toBe(0);
      const bytes = await a.read(VIEWS);
      expect(await b.read(VIEWS)).toBe(bytes);
      // No timestamps, no absolute paths: the file must be committable and
      // identical from any machine and any moment.
      expect(bytes).not.toMatch(/\d{4}-\d{2}-\d{2}/);
      expect(bytes).not.toContain(a.docsDir);
      expect(bytes).not.toContain(b.docsDir);
    } finally {
      await a.destroy();
      await b.destroy();
    }
  });

  it("two single moves into different subsystems change disjoint line sets — the git-mergeable shape", async () => {
    // Base: two empty subsystems, two unfiled services. Variant A files
    // payment-service into payments/; variant B files checkout-web into web/.
    const base: Record<string, string> = {
      "architecture/landscape.likec4": LANDSCAPE,
      "services/payments/subsystem.yaml": "",
      "services/web/subsystem.yaml": "",
      "services/payment-service/spec.md": "---\nservice: payment-service\n---\n\n# payment-service\n",
      "services/checkout-web/spec.md": "---\nservice: checkout-web\n---\n\n# checkout-web\n",
    };
    const variantA: Record<string, string> = { ...base };
    delete variantA["services/payment-service/spec.md"];
    variantA["services/payments/payment-service/spec.md"] = base["services/payment-service/spec.md"]!;
    const variantB: Record<string, string> = { ...base };
    delete variantB["services/checkout-web/spec.md"];
    variantB["services/web/checkout-web/spec.md"] = base["services/checkout-web/spec.md"]!;

    const render = async (files: Record<string, string>): Promise<string[]> => {
      const p = await makeProject(files);
      try {
        expect((await runLoam(p.workDir, "subsystem", "sync")).code).toBe(0);
        return (await p.read(VIEWS)).split("\n");
      } finally {
        await p.destroy();
      }
    };
    const baseLines = await render(base);
    const aLines = await render(variantA);
    const bLines = await render(variantB);
    const added = (variant: string[]): string[] => {
      const pool = [...baseLines];
      return variant.filter((line) => {
        const i = pool.indexOf(line);
        if (i === -1) return true;
        pool.splice(i, 1);
        return false;
      });
    };
    const addedA = added(aLines);
    const addedB = added(bLines);
    // A filed member turns an empty view into a boxed one, so the move adds
    // the box's two lines beside the include. Three lines instead of one, and
    // every line that NAMES anything is still disjoint between the two
    // variants — which is the line-orientation this file promises.
    expect(addedA).toEqual(["    group 'payments' {", "      include paymentService", "    }"]);
    expect(addedB).toEqual(["    group 'web' {", "      include checkoutWeb", "    }"]);
    const naming = (lines: string[]): string[] => lines.filter((l) => l.trim() !== "}");
    expect(naming(addedA).filter((l) => naming(addedB).includes(l))).toEqual([]);
    // A bare `}` is structural and repeats by construction, so it is excluded
    // here rather than asserted away: whether git merges the two moves is not
    // a question about identical line TEXT, and it is answered where it can
    // be answered honestly — by git itself, in test/subsystem-move.test.ts's
    // "two moves into DIFFERENT groups merge without intervention".
    expect(addedA.filter((l) => l.trim() === "}")).toEqual(["    }"]);
  });

  /** A landscape whose services are nested inside `group` elements, as ordinary grouped C4 draws them. */
  function groupedLandscape(model: string): string {
    return `specification {\n  element softwareSystem\n  element group\n}\n\nmodel {\n${model}}\n\nviews {\n  view landscape {\n    include *\n  }\n}\n`;
  }

  const SPEC = (id: string): string => `---\nservice: ${id}\n---\n\n# ${id}\n`;

  it("draws the model's OWN box when one element holds exactly the subsystem's members", async () => {
    // The members are nested in the map, and `mp.core` holds them and nothing
    // else — so the view includes it and the renderer nests the leaves inside
    // the box the author drew, under the author's own title. Measured:
    // including the ancestor alone renders one empty box, the leaves alone
    // render flat, so both lines are needed.
    const p = await makeProject({
      "architecture/landscape.likec4": groupedLandscape(
        "  mp = group 'Marketplace' {\n    core = group 'Core' {\n" +
          "      paymentService = softwareSystem 'payment-service'\n" +
          "      checkoutWeb = softwareSystem 'checkout-web'\n    }\n  }\n",
      ),
      "services/payments/subsystem.yaml": "title: Payments\n",
      "services/payments/payment-service/spec.md": SPEC("payment-service"),
      "services/payments/checkout-web/spec.md": SPEC("checkout-web"),
    });
    try {
      expect((await runLoam(p.workDir, "subsystem", "sync")).code).toBe(0);
      const bytes = await p.read(VIEWS);
      expect(bytes).toContain(
        "    title 'Payments'\n" +
          "    include mp.core\n" +
          "    include mp.core.checkoutWeb\n" +
          "    include mp.core.paymentService\n",
      );
      // No synthetic box: one boundary, the author's.
      expect(bytes).not.toContain("group '");
      expect(bytes).not.toContain("// model:");
    } finally {
      await p.destroy();
    }
  });

  it("draws NO box and says why when the containing element holds services from outside the subsystem", async () => {
    // The drift case: the directory tree and the map disagree about this
    // group. A synthetic box would look identical whether or not they agree,
    // so loam draws none and writes one comment — outside the view body, and
    // graded by nothing.
    const p = await makeProject({
      "architecture/landscape.likec4": groupedLandscape(
        "  mp = group 'Marketplace' {\n    core = group 'Core' {\n" +
          "      paymentService = softwareSystem 'payment-service'\n" +
          "      checkoutWeb = softwareSystem 'checkout-web'\n    }\n  }\n",
      ),
      "services/payments/subsystem.yaml": "title: Payments\n",
      "services/payments/payment-service/spec.md": SPEC("payment-service"),
      // checkout-web sits under `mp.core` in the map and OUTSIDE payments/ in
      // the tree — exactly what one `loam subsystem move` leaves behind.
      "services/checkout-web/spec.md": SPEC("checkout-web"),
    });
    try {
      expect((await runLoam(p.workDir, "subsystem", "sync")).code).toBe(0);
      const bytes = await p.read(VIEWS);
      expect(bytes).toContain("  // model: no boundary — mp.core also holds services outside this subsystem.\n");
      expect(bytes).not.toContain("include mp.core\n");
      expect(bytes).toContain("    include mp.core.paymentService\n");
    } finally {
      await p.destroy();
    }
  });

  it("says so plainly when the members share no containing element at all", async () => {
    const p = await makeProject({
      "architecture/landscape.likec4": groupedLandscape(
        "  alpha = group 'Alpha' {\n    paymentService = softwareSystem 'payment-service'\n  }\n" +
          "  beta = group 'Beta' {\n    checkoutWeb = softwareSystem 'checkout-web'\n  }\n",
      ),
      "services/payments/subsystem.yaml": "title: Payments\n",
      "services/payments/payment-service/spec.md": SPEC("payment-service"),
      "services/payments/checkout-web/spec.md": SPEC("checkout-web"),
    });
    try {
      expect((await runLoam(p.workDir, "subsystem", "sync")).code).toBe(0);
      expect(await p.read(VIEWS)).toContain(
        "  // model: no boundary — these members do not share a containing element.\n",
      );
    } finally {
      await p.destroy();
    }
  });

  it("boxes the DIRECTORY tree when the map draws no boundary at all — a parent shows its children as boxes", async () => {
    // The fleet the reports describe: every service top-level in the map, the
    // subsystem split living only in the directories. There is no authored
    // box to agree with, so the view draws the tree's own — nested, so a
    // parent subsystem is not one undifferentiated pile.
    const p = await makeProject({
      "architecture/landscape.likec4": LANDSCAPE,
      "services/api/subsystem.yaml": "title: API\n",
      "services/api/rest/subsystem.yaml": "title: REST v2\n",
      "services/api/rest/payment-service/spec.md": SPEC("payment-service"),
      "services/api/checkout-web/spec.md": SPEC("checkout-web"),
    });
    try {
      expect((await runLoam(p.workDir, "subsystem", "sync")).code).toBe(0);
      const bytes = await p.read(VIEWS);
      expect(bytes).toContain(
        "  view subsystem_api {\n" +
          "    title 'API'\n" +
          "    group 'API' {\n" +
          "      group 'REST v2' {\n" +
          "        include paymentService\n" +
          "      }\n" +
          "      include checkoutWeb\n" +
          "    }\n" +
          "  }\n",
      );
      // The child's own view is the same box without the parent around it.
      expect(bytes).toContain(
        "  view subsystem_api__rest {\n    title 'REST v2'\n    group 'REST v2' {\n      include paymentService\n    }\n  }\n",
      );
      expect(bytes).not.toContain("// model:");
    } finally {
      await p.destroy();
    }
  });

  it("view identifiers are injective: a_b, and b under a, render three distinct ids the renderer accepts", async () => {
    // The old folding (every non-identifier byte AND the join separator to a
    // single `_`) rendered `subsystem_a_b` for BOTH the subsystem named `a_b`
    // and the subsystem `b` nested under `a` — three distinct healthy names,
    // a green `validate --all`, and a duplicate view id the LikeC4 renderer
    // refuses the whole architecture/ project over. The encoding escapes
    // every such byte to `_` + two hex digits and joins nesting on `__`, so
    // no two legal paths can share an id.
    const p = await makeProject({
      "architecture/landscape.likec4": LANDSCAPE,
      "services/a/subsystem.yaml": "",
      "services/a/b/subsystem.yaml": "",
      "services/a_b/subsystem.yaml": "",
    });
    try {
      expect((await runLoam(p.workDir, "subsystem", "sync")).code).toBe(0);
      const bytes = await p.read(VIEWS);
      const ids = [...bytes.matchAll(/^ {2}view (\S+) \{/gm)].map((m) => m[1]!);
      expect(ids).toEqual(["subsystem_a", "subsystem_a__b", "subsystem_a_5fb"]);
      expect(new Set(ids).size).toBe(ids.length);
    } finally {
      await p.destroy();
    }
  });

  it("an empty subsystem renders an empty view body, and a member nothing models is omitted from the includes", async () => {
    const p = await makeProject({
      "architecture/landscape.likec4": LANDSCAPE,
      "services/payments/subsystem.yaml": "title: Payments\n",
      // unmodelled-service has no landscape element: landscape.service-unmodelled
      // already errors on it, so the views omit it rather than invent an id.
      "services/payments/unmodelled-service/spec.md": "---\nservice: unmodelled-service\n---\n\n# u\n",
      "services/empty-group/subsystem.yaml": "",
    });
    try {
      expect((await runLoam(p.workDir, "subsystem", "sync")).code).toBe(0);
      const bytes = await p.read(VIEWS);
      // A title-only body: the marker carries no title, so the DIRECTORY name
      // is the label — an empty subsystem is still a named box, never an id.
      expect(bytes).toContain("  view subsystem_empty_2dgroup {\n    title 'empty-group'\n  }\n");
      expect(bytes).not.toContain("unmodelled");
    } finally {
      await p.destroy();
    }
  });

  it("escapes a marker's words: an apostrophe, a backslash and a view-injection attempt all land as ONE title line", async () => {
    // The marker validates that `title` is a string and nothing else, so this
    // is a `subsystem.yaml` a human may legally write. Written raw it is not a
    // parse error — it is 0 errors and an INJECTED view, and an injected id
    // equal to an authored one replaces that author's view in the renderer.
    const p = await makeProject({
      "architecture/landscape.likec4": LANDSCAPE,
      "services/payments/subsystem.yaml":
        "title: 'Ops'' tooling \\ C:\\path'' } view evil { include checkoutWeb'\n" +
        "description: |\n  line one\n  line two\n",
      "services/payments/payment-service/spec.md": "---\nservice: payment-service\n---\n\n# p\n",
    });
    try {
      expect((await runLoam(p.workDir, "subsystem", "sync")).code).toBe(0);
      const bytes = await p.read(VIEWS);
      expect(bytes).toContain(
        "    title 'Ops\\' tooling \\\\ C:\\\\path\\' } view evil { include checkoutWeb'\n",
      );
      // A YAML block scalar is several lines; the file's contract is not.
      expect(bytes).toContain("    description 'line one line two'\n");
      // The injection attempt minted no view: exactly one id in the file.
      expect([...bytes.matchAll(/^ {2}view (\S+) \{/gm)].map((m) => m[1])).toEqual(["subsystem_payments"]);
    } finally {
      await p.destroy();
    }
  });

  it("the renderer's own output parses: the generated file loads with the landscape, and the title round-trips", async () => {
    // loam never parses this file (rule 26, and `documents.ts` excludes it from
    // every project load) — which is exactly why nothing else would catch a bad
    // escape: `likec4 export json` logs an error and still exits 0. The
    // renderer is the only reader this file has, so the suite stands in for it
    // once. A TEST reading the file is not loam reading it.
    const raw = "Ops' tooling \\ C:\\path' } view evil { include checkoutWeb";
    const p = await makeProject({
      "architecture/landscape.likec4": LANDSCAPE,
      "services/payments/subsystem.yaml":
        "title: 'Ops'' tooling \\ C:\\path'' } view evil { include checkoutWeb'\n",
      "services/payments/payment-service/spec.md": "---\nservice: payment-service\n---\n\n# p\n",
    });
    try {
      expect((await runLoam(p.workDir, "subsystem", "sync")).code).toBe(0);
      const loaded = await LikeC4.fromWorkspace(join(p.docsDir, "architecture"), { logger: false });
      try {
        expect(loaded.getErrors()).toEqual([]);
        const model = (await loaded.parsedModel()) as unknown as {
          $data?: { views?: Record<string, { title?: string }> };
        };
        const views = model.$data?.views ?? {};
        expect(views["subsystem_payments"]?.title).toBe(raw);
        // No injected view, under any id: the escape held at the parser too.
        expect(Object.keys(views).filter((id) => id.startsWith("subsystem_"))).toEqual(["subsystem_payments"]);
      } finally {
        await loaded.dispose();
      }
    } finally {
      await p.destroy();
    }
  });

  it("is idempotent, and removes the file when the last subsystem is gone", async () => {
    const p = await makeProject(nestedFixture());
    try {
      expect(JSON.parse((await runLoam(p.workDir, "subsystem", "sync", "--json")).stdout).action).toBe("created");
      const before = await treeHashes(p.docsDir);
      const again = await runLoam(p.workDir, "subsystem", "sync", "--json");
      expect(JSON.parse(again.stdout).action).toBe("current");
      expect(await treeHashes(p.docsDir)).toEqual(before);

      // Unfile the fleet by hand (the move verb is its own suite): with zero
      // subsystems the generated file must be ABSENT, and sync is what removes it.
      await p.write("services/payment-service/spec.md", await p.read("services/payments/payment-service/spec.md"));
      await p.write("services/payment-service/model.likec4", await p.read("services/payments/payment-service/model.likec4"));
      await p.write("services/payment-service/openapi.yaml", await p.read("services/payments/payment-service/openapi.yaml"));
      await rm(join(p.docsDir, "services", "payments"), { recursive: true });
      const removed = await runLoam(p.workDir, "subsystem", "sync", "--json");
      expect(JSON.parse(removed.stdout).action).toBe("removed");
      expect(p.exists(VIEWS)).toBe(false);
    } finally {
      await p.destroy();
    }
  });
});

describe("validate --all — subsystem.views-stale", () => {
  it("subsystems with no views file: exactly one error, naming the file and `loam subsystem sync`", async () => {
    const p = await makeProject(nestedFixture());
    try {
      const res = await runLoam(p.workDir, "validate", "--all", "--json");
      expect(res.code).toBe(1);
      const findings = subsystemFindings(res.stdout);
      expect(findings).toHaveLength(1);
      expect(findings[0]).toMatchObject({
        severity: "error",
        code: "subsystem.views-stale",
        subject: "architecture/subsystems.likec4",
      });
      expect(findings[0]!.message).toContain("loam subsystem sync");
      // The file does not exist yet, so the location is the directory the
      // regenerator writes into — never a `primary` pointing at nothing.
      expect(findings[0]!.locations).toEqual([{ path: "architecture", role: "scope" }]);
    } finally {
      await p.destroy();
    }
  });

  it("one `loam subsystem sync` repairs it: the fleet is green after, and byte-stable on re-validate", async () => {
    const p = await makeProject(nestedFixture());
    try {
      expect((await runLoam(p.workDir, "subsystem", "sync")).code).toBe(0);
      const res = await runLoam(p.workDir, "validate", "--all", "--json");
      expect(res.code).toBe(0);
      expect(subsystemFindings(res.stdout)).toEqual([]);
    } finally {
      await p.destroy();
    }
  });

  it("the writers read the same documents the grader does: a use-case document's binding is not a stale file no command can repair", async () => {
    // `validate` grades this file against the whole `architecture/` PROJECT —
    // the landscape merged with every `usecases/*.likec4`, which may declare
    // elements of its own. While `sync` rendered from the landscape FILE
    // alone, one such element bound to a filed service was enough to make
    // `sync` answer `current` while `validate --all` reported
    // `subsystem.views-stale` and named `sync` as the repair. Reproduced on
    // examples/docs before the writers were pointed at the project.
    const files = nestedFixture();
    files["services/payments/audit-service/spec.md"] =
      "---\nservice: audit-service\nstatus: draft\n---\n\n# audit-service\n";
    files["architecture/usecases/uc.likec4"] =
      "model {\n" +
      "  auditService = softwareSystem 'audit-service' {\n" +
      "    metadata {\n" +
      "      service 'audit-service'\n" +
      "    }\n" +
      "  }\n" +
      "}\n";
    const p = await makeProject(files);
    try {
      expect((await runLoam(p.workDir, "subsystem", "sync")).code).toBe(0);
      expect(await p.read(VIEWS)).toContain("include auditService");
      const res = await runLoam(p.workDir, "validate", "--all", "--json");
      expect(subsystemFindings(res.stdout)).toEqual([]);
    } finally {
      await p.destroy();
    }
  });

  it("a hand-edited views file reads stale — the byte compare, not a parse, is the check", async () => {
    const p = await makeProject(nestedFixture());
    try {
      await runLoam(p.workDir, "subsystem", "sync");
      await p.write(VIEWS, (await p.read(VIEWS)) + "// a hand edit\n");
      const res = await runLoam(p.workDir, "validate", "--all", "--json");
      expect(res.code).toBe(1);
      expect(subsystemFindings(res.stdout).map((f) => f.code)).toEqual(["subsystem.views-stale"]);
    } finally {
      await p.destroy();
    }
  });

  it("zero subsystems and no file is silence; zero subsystems and a leftover file is stale", async () => {
    const flat = await makeProject(coherentFixture());
    try {
      const clean = await runLoam(flat.workDir, "validate", "--all", "--json");
      expect(clean.code).toBe(0);
      expect(subsystemFindings(clean.stdout)).toEqual([]);
      await flat.write(VIEWS, "views {\n}\n");
      const stale = await runLoam(flat.workDir, "validate", "--all", "--json");
      expect(stale.code).toBe(1);
      expect(subsystemFindings(stale.stdout).map((f) => f.code)).toEqual(["subsystem.views-stale"]);
    } finally {
      await flat.destroy();
    }
  });
});

describe("a Windows checkout: line endings are not a stale render", () => {
  // The generated file is the one file loam forbids editing by hand, and
  // `core.autocrlf` is Git for Windows' installer default while a docs repo
  // ships no `.gitattributes` — so an ordinary clone rewrites every line of it
  // and changes not one fact. Under a byte compare that read as stale, and the
  // repair the finding advertises made it worse: `loam subsystem sync` rewrote
  // with LF, git reported the file permanently modified, and the next checkout
  // put the CRLF back. Measured on this repository's own `examples/docs`: one
  // error where every other check was green.
  const crlf = (text: string): string => text.replace(/\n/g, "\r\n");

  it("reads a CRLF-rewritten generated views file as agreeing with the tree", async () => {
    const p = await makeProject(nestedFixture());
    try {
      expect((await runLoam(p.workDir, "subsystem", "sync")).code).toBe(0);
      await p.write(VIEWS, crlf(await p.read(VIEWS)));
      const res = await runLoam(p.workDir, "validate", "--all", "--json");
      expect(res.code, res.stdout).toBe(0);
      expect(subsystemFindings(res.stdout)).toEqual([]);
    } finally {
      await p.destroy();
    }
  });

  it("still reads a real edit made on a CRLF checkout as stale — normalising endings is not normalising content", async () => {
    // The converse, so the check does not go blind: a compare that ignored
    // line endings by ignoring the comparison would pass the case above too.
    const p = await makeProject(nestedFixture());
    try {
      expect((await runLoam(p.workDir, "subsystem", "sync")).code).toBe(0);
      await p.write(VIEWS, crlf((await p.read(VIEWS)) + "// a hand edit\n"));
      const res = await runLoam(p.workDir, "validate", "--all", "--json");
      expect(res.code).toBe(1);
      const findings = subsystemFindings(res.stdout);
      expect(findings.map((f) => f.code)).toEqual(["subsystem.views-stale"]);
      // The file the message names — not the landscape the target fallback
      // would otherwise supply.
      expect(findings[0]!.locations).toEqual([
        { path: "architecture/subsystems.likec4", role: "primary" },
      ]);
    } finally {
      await p.destroy();
    }
  });
});

describe("validate --all — subsystem.view-id-collision", () => {
  /** `nestedFixture()` with the landscape authoring the view id the generator mints. */
  function collidingFixture(viewId: string): Record<string, string> {
    const files = nestedFixture();
    files["architecture/landscape.likec4"] = LANDSCAPE.replace(
      "views {",
      `views {
  view ${viewId} {
    include *
  }
`,
    );
    return files;
  }

  it("an authored view claiming a GENERATED id is an error naming the subsystem it belongs to", async () => {
    // Measured against likec4@1.59.2: with both files present the renderer
    // refuses the whole architecture/ project with two `Duplicate view`
    // diagnostics — and every other check in this run stays green, which is
    // the hole this code closes.
    const p = await makeProject(collidingFixture("subsystem_payments"));
    try {
      await runLoam(p.workDir, "subsystem", "sync");
      const res = await runLoam(p.workDir, "validate", "--all", "--json");
      expect(res.code).toBe(1);
      const hits = subsystemFindings(res.stdout).filter((f) => f.code === "subsystem.view-id-collision");
      expect(hits).toHaveLength(1);
      expect(hits[0]).toMatchObject({ severity: "error", subject: "subsystem_payments" });
      expect(hits[0]!.message).toContain("services/payments/");
      expect(hits[0]!.message).toContain("architecture/subsystems.likec4");
    } finally {
      await p.destroy();
    }
  });

  it("names the CLAIMANT file as the location, even when the claim came from a document of the author's own", async () => {
    // The shape a user reported: a hand-authored `architecture/<own>.likec4`
    // beside the generated file. The message tells them to rename the view in
    // their own document, while the target fallback used to send an editor to
    // architecture/landscape.likec4 — a file that has nothing to rename.
    const files = nestedFixture();
    files["architecture/obm-subsystems.likec4"] = "views {\n  view subsystem_payments {\n    include *\n  }\n}\n";
    const p = await makeProject(files);
    try {
      const res = await runLoam(p.workDir, "validate", "--all", "--json");
      const hits = subsystemFindings(res.stdout).filter((f) => f.code === "subsystem.view-id-collision");
      expect(hits).toHaveLength(1);
      expect(hits[0]!.locations).toEqual([
        { path: "architecture/obm-subsystems.likec4", role: "primary" },
      ]);
    } finally {
      await p.destroy();
    }
  });

  it("fires on the generated id even before `subsystem sync` has written the file", async () => {
    // The collision is a fact about what loam WILL mint, not about bytes on
    // disk: a fleet that has not synced yet is already broken for anyone who
    // syncs, and `subsystem.views-stale` is about to make them.
    const p = await makeProject(collidingFixture("subsystem_payments"));
    try {
      const res = await runLoam(p.workDir, "validate", "--all", "--json");
      expect(res.code).toBe(1);
      const codes = subsystemFindings(res.stdout).map((f) => f.code).sort();
      expect(codes).toEqual(["subsystem.view-id-collision", "subsystem.views-stale"]);
    } finally {
      await p.destroy();
    }
  });

  it("a `subsystem_`-looking id matching no subsystem is NOT refused — it breaks nothing yet", async () => {
    // Deliberate, and the reason is in views/ids.ts: refusing a name that
    // harms nobody would be loam inventing a rule. The day somebody creates
    // that subsystem, the generator mints the id and the case above fires.
    const p = await makeProject(collidingFixture("subsystem_nosuchgroup"));
    try {
      await runLoam(p.workDir, "subsystem", "sync");
      const res = await runLoam(p.workDir, "validate", "--all", "--json");
      expect(subsystemFindings(res.stdout).map((f) => f.code)).not.toContain("subsystem.view-id-collision");
    } finally {
      await p.destroy();
    }
  });

  it("an ordinary authored view is never refused, and a fleet with no subsystems is silent", async () => {
    // The harness landscape already declares `view landscape`; a fleet with no
    // subsystems generates no ids at all, so there is nothing to collide with.
    const p = await makeProject(coherentFixture());
    try {
      const res = await runLoam(p.workDir, "validate", "--all", "--json");
      expect(res.code).toBe(0);
      expect(subsystemFindings(res.stdout).map((f) => f.code)).not.toContain("subsystem.view-id-collision");
    } finally {
      await p.destroy();
    }
  });

  it("says nothing under a single-target run, where the tree is not walked", async () => {
    // loam's could-not-look rule: `validate --service` loads no fleet tree, so
    // the generated ids are unknown and the question is unanswerable. Silence,
    // never a half-answer.
    const p = await makeProject(collidingFixture("subsystem_payments"));
    try {
      await runLoam(p.workDir, "subsystem", "sync");
      const res = await runLoam(p.workDir, "validate", "--service", "payment-service", "--json");
      expect(res.stdout).not.toContain("subsystem.view-id-collision");
    } finally {
      await p.destroy();
    }
  });
});
