/**
 * The generated subsystem views file, end to end: `loam subsystem sync`
 * renders `architecture/subsystems.likec4` deterministically from the tree,
 * and `validate --all` grades staleness as exactly ONE error on exactly one
 * file, by byte comparison — never by parsing.
 *
 * The two properties worth naming are exit criteria of the roadmap item:
 * byte-reproducibility (no timestamps, no absolute paths, no readdir-order
 * dependence — the file renders identically on any machine from the same
 * committed bytes) and line-orientation (one `include` per line, subsystems
 * sorted by path, members by id — so two concurrent moves into different
 * groups touch different lines and git merges the generated file without
 * intervention).
 */
import { describe, expect, it } from "vitest";
import { rm } from "node:fs/promises";
import { join } from "node:path";
import {
  coherentFixture,
  LANDSCAPE,
  makeProject,
  runLoam,
  treeHashes,
} from "./helpers/harness.js";

interface JsonFinding {
  severity: string;
  code: string;
  message: string;
  subject?: string;
}

function subsystemFindings(stdout: string): JsonFinding[] {
  const payload = JSON.parse(stdout) as { targets: Array<{ findings: JsonFinding[] }> };
  return payload.targets.flatMap((t) => t.findings).filter((f) => f.code.startsWith("subsystem."));
}

/** `coherentFixture()` with payment-service filed into a marked subsystem. */
function nestedFixture(): Record<string, string> {
  const files: Record<string, string> = {};
  for (const [path, content] of Object.entries(coherentFixture())) {
    files[path.replace(/^services\/payment-service\//, "services/payments/payment-service/")] = content;
  }
  files["services/payments/subsystem.yaml"] = "title: Payments\n";
  return files;
}

const VIEWS = "architecture/subsystems.likec4";

describe("loam subsystem sync — the renderer", () => {
  it("writes one view per subsystem, sorted by path, one include per line, members resolved to landscape ELEMENT ids", async () => {
    // Two subsystems out of path order on disk plus an unfiled service; the
    // landscape names elements whose ids differ from the service ids (the
    // harness LANDSCAPE joins by TITLE), which is exactly why includes must go
    // through the element→service join rather than spelling service ids.
    const files = nestedFixture();
    files["services/web/subsystem.yaml"] = "";
    files["services/web/checkout-web/spec.md"] = "---\nservice: checkout-web\nstatus: draft\n---\n\n# checkout-web\n";
    const p = await makeProject(files);
    try {
      const res = await runLoam(p.workDir, "subsystem", "sync", "--json");
      expect(res.code).toBe(0);
      const payload = JSON.parse(res.stdout);
      expect(payload.ok).toBe(true);
      expect(payload.path).toBe(VIEWS);
      expect(payload.action).toBe("created");
      expect(payload.subsystems).toBe(2);
      // The exact bytes are the contract: deterministic, line-oriented, no
      // timestamps, no absolute paths. Pinning them whole is what makes any
      // accidental format drift loud.
      expect(await p.read(VIEWS)).toBe(
        "// generated by loam — the subsystem tree under services/, one view per subsystem.\n" +
          "// Do not edit: `loam subsystem sync` regenerates this file from the directories,\n" +
          "// and `loam validate --all` reports `subsystem.views-stale` when it drifts.\n" +
          "\n" +
          "views {\n" +
          "  // services/payments\n" +
          "  view subsystem_payments {\n" +
          "    include paymentService\n" +
          "  }\n" +
          "\n" +
          "  // services/web\n" +
          "  view subsystem_web {\n" +
          "    include checkoutWeb\n" +
          "  }\n" +
          "}\n",
      );
    } finally {
      await p.destroy();
    }
  });

  it("is byte-reproducible: the same logical tree written in a different order renders identical bytes", async () => {
    const forward = nestedFixture();
    forward["services/web/subsystem.yaml"] = "";
    forward["services/web/checkout-web/spec.md"] = "---\nservice: checkout-web\n---\n\n# checkout-web\n";
    const backward: Record<string, string> = {};
    for (const key of Object.keys(forward).reverse()) backward[key] = forward[key]!;
    const a = await makeProject(forward);
    const b = await makeProject(backward);
    try {
      expect((await runLoam(a.workDir, "subsystem", "sync")).code).toBe(0);
      expect((await runLoam(b.workDir, "subsystem", "sync")).code).toBe(0);
      const bytes = await a.read(VIEWS);
      expect(await b.read(VIEWS)).toBe(bytes);
      // No timestamps, no absolute paths: the file must be committable and
      // identical from any machine and any moment.
      expect(bytes).not.toMatch(/\d{4}-\d{2}-\d{2}/);
      expect(bytes).not.toContain(a.docsDir);
      expect(bytes).not.toContain(b.docsDir);
    } finally {
      await a.destroy();
      await b.destroy();
    }
  });

  it("two single moves into different subsystems change disjoint line sets — the git-mergeable shape", async () => {
    // Base: two empty subsystems, two unfiled services. Variant A files
    // payment-service into payments/; variant B files checkout-web into web/.
    const base: Record<string, string> = {
      "architecture/landscape.likec4": LANDSCAPE,
      "services/payments/subsystem.yaml": "",
      "services/web/subsystem.yaml": "",
      "services/payment-service/spec.md": "---\nservice: payment-service\n---\n\n# payment-service\n",
      "services/checkout-web/spec.md": "---\nservice: checkout-web\n---\n\n# checkout-web\n",
    };
    const variantA: Record<string, string> = { ...base };
    delete variantA["services/payment-service/spec.md"];
    variantA["services/payments/payment-service/spec.md"] = base["services/payment-service/spec.md"]!;
    const variantB: Record<string, string> = { ...base };
    delete variantB["services/checkout-web/spec.md"];
    variantB["services/web/checkout-web/spec.md"] = base["services/checkout-web/spec.md"]!;

    const render = async (files: Record<string, string>): Promise<string[]> => {
      const p = await makeProject(files);
      try {
        expect((await runLoam(p.workDir, "subsystem", "sync")).code).toBe(0);
        return (await p.read(VIEWS)).split("\n");
      } finally {
        await p.destroy();
      }
    };
    const baseLines = await render(base);
    const aLines = await render(variantA);
    const bLines = await render(variantB);
    const added = (variant: string[]): string[] => {
      const pool = [...baseLines];
      return variant.filter((line) => {
        const i = pool.indexOf(line);
        if (i === -1) return true;
        pool.splice(i, 1);
        return false;
      });
    };
    const addedA = added(aLines);
    const addedB = added(bLines);
    expect(addedA).toEqual(["    include paymentService"]);
    expect(addedB).toEqual(["    include checkoutWeb"]);
    // Different groups, different lines: git merges the two moves cleanly.
    expect(addedA.filter((l) => addedB.includes(l))).toEqual([]);
  });

  it("view identifiers are injective: a_b, and b under a, render three distinct ids the renderer accepts", async () => {
    // The old folding (every non-identifier byte AND the join separator to a
    // single `_`) rendered `subsystem_a_b` for BOTH the subsystem named `a_b`
    // and the subsystem `b` nested under `a` — three distinct healthy names,
    // a green `validate --all`, and a duplicate view id the LikeC4 renderer
    // refuses the whole architecture/ project over. The encoding escapes
    // every such byte to `_` + two hex digits and joins nesting on `__`, so
    // no two legal paths can share an id.
    const p = await makeProject({
      "architecture/landscape.likec4": LANDSCAPE,
      "services/a/subsystem.yaml": "",
      "services/a/b/subsystem.yaml": "",
      "services/a_b/subsystem.yaml": "",
    });
    try {
      expect((await runLoam(p.workDir, "subsystem", "sync")).code).toBe(0);
      const bytes = await p.read(VIEWS);
      const ids = [...bytes.matchAll(/^ {2}view (\S+) \{/gm)].map((m) => m[1]!);
      expect(ids).toEqual(["subsystem_a", "subsystem_a__b", "subsystem_a_5fb"]);
      expect(new Set(ids).size).toBe(ids.length);
    } finally {
      await p.destroy();
    }
  });

  it("an empty subsystem renders an empty view body, and a member nothing models is omitted from the includes", async () => {
    const p = await makeProject({
      "architecture/landscape.likec4": LANDSCAPE,
      "services/payments/subsystem.yaml": "title: Payments\n",
      // unmodelled-service has no landscape element: landscape.service-unmodelled
      // already errors on it, so the views omit it rather than invent an id.
      "services/payments/unmodelled-service/spec.md": "---\nservice: unmodelled-service\n---\n\n# u\n",
      "services/empty-group/subsystem.yaml": "",
    });
    try {
      expect((await runLoam(p.workDir, "subsystem", "sync")).code).toBe(0);
      const bytes = await p.read(VIEWS);
      expect(bytes).toContain("  view subsystem_empty_2dgroup {\n  }\n");
      expect(bytes).not.toContain("unmodelled");
    } finally {
      await p.destroy();
    }
  });

  it("is idempotent, and removes the file when the last subsystem is gone", async () => {
    const p = await makeProject(nestedFixture());
    try {
      expect(JSON.parse((await runLoam(p.workDir, "subsystem", "sync", "--json")).stdout).action).toBe("created");
      const before = await treeHashes(p.docsDir);
      const again = await runLoam(p.workDir, "subsystem", "sync", "--json");
      expect(JSON.parse(again.stdout).action).toBe("current");
      expect(await treeHashes(p.docsDir)).toEqual(before);

      // Unfile the fleet by hand (the move verb is its own suite): with zero
      // subsystems the generated file must be ABSENT, and sync is what removes it.
      await p.write("services/payment-service/spec.md", await p.read("services/payments/payment-service/spec.md"));
      await p.write("services/payment-service/model.likec4", await p.read("services/payments/payment-service/model.likec4"));
      await p.write("services/payment-service/openapi.yaml", await p.read("services/payments/payment-service/openapi.yaml"));
      await rm(join(p.docsDir, "services", "payments"), { recursive: true });
      const removed = await runLoam(p.workDir, "subsystem", "sync", "--json");
      expect(JSON.parse(removed.stdout).action).toBe("removed");
      expect(p.exists(VIEWS)).toBe(false);
    } finally {
      await p.destroy();
    }
  });
});

describe("validate --all — subsystem.views-stale", () => {
  it("subsystems with no views file: exactly one error, naming the file and `loam subsystem sync`", async () => {
    const p = await makeProject(nestedFixture());
    try {
      const res = await runLoam(p.workDir, "validate", "--all", "--json");
      expect(res.code).toBe(1);
      const findings = subsystemFindings(res.stdout);
      expect(findings).toHaveLength(1);
      expect(findings[0]).toMatchObject({
        severity: "error",
        code: "subsystem.views-stale",
        subject: "architecture/subsystems.likec4",
      });
      expect(findings[0]!.message).toContain("loam subsystem sync");
    } finally {
      await p.destroy();
    }
  });

  it("one `loam subsystem sync` repairs it: the fleet is green after, and byte-stable on re-validate", async () => {
    const p = await makeProject(nestedFixture());
    try {
      expect((await runLoam(p.workDir, "subsystem", "sync")).code).toBe(0);
      const res = await runLoam(p.workDir, "validate", "--all", "--json");
      expect(res.code).toBe(0);
      expect(subsystemFindings(res.stdout)).toEqual([]);
    } finally {
      await p.destroy();
    }
  });

  it("a hand-edited views file reads stale — the byte compare, not a parse, is the check", async () => {
    const p = await makeProject(nestedFixture());
    try {
      await runLoam(p.workDir, "subsystem", "sync");
      await p.write(VIEWS, (await p.read(VIEWS)) + "// a hand edit\n");
      const res = await runLoam(p.workDir, "validate", "--all", "--json");
      expect(res.code).toBe(1);
      expect(subsystemFindings(res.stdout).map((f) => f.code)).toEqual(["subsystem.views-stale"]);
    } finally {
      await p.destroy();
    }
  });

  it("zero subsystems and no file is silence; zero subsystems and a leftover file is stale", async () => {
    const flat = await makeProject(coherentFixture());
    try {
      const clean = await runLoam(flat.workDir, "validate", "--all", "--json");
      expect(clean.code).toBe(0);
      expect(subsystemFindings(clean.stdout)).toEqual([]);
      await flat.write(VIEWS, "views {\n}\n");
      const stale = await runLoam(flat.workDir, "validate", "--all", "--json");
      expect(stale.code).toBe(1);
      expect(subsystemFindings(stale.stdout).map((f) => f.code)).toEqual(["subsystem.views-stale"]);
    } finally {
      await flat.destroy();
    }
  });
});
