/**
 * The generated views file: `architecture/subsystems.likec4`, one LikeC4 view
 * per subsystem enumerating the services beneath it. GENERATED, never
 * authored — authored bytes stay authored (archive's verbatim-splice promise),
 * so the tree is mirrored into a file of its own that `loam subsystem sync`
 * owns outright, and staleness against the tree is a byte compare
 * (`subsystem.views-stale` in `validate --all`), never a parse: a spike
 * confirmed a views-only document does NOT parse standalone (its `include`
 * lines reference elements the landscape defines), so nothing in loam ever
 * loads this file (and rule 26 does not change that: this file is GENERATED and
 * holds STATIC views, whose contents loam may not read in any document) — only
 * the LikeC4 renderer, which merges the whole `architecture/` project per
 * likec4.config.json, resolves it.
 *
 * The output is deterministic and line-oriented, and both halves are the
 * contract: subsystems sorted by path, members sorted by id, ONE `include`
 * per line — so two concurrent moves into different groups touch different
 * lines and git merges the file without intervention, exactly as the
 * service-grouped landscape splice already achieves. Byte-reproducible on any
 * machine: no timestamps, no absolute paths, no readdir-order dependence (the
 * walk sorts, and every list is re-sorted here). Plain lexicographic sorts on
 * purpose — the ids' own grammar is ASCII, an INVALID name is still ordered
 * deterministically, and `compareIds`' numeric tokenizing lives in `repo/`,
 * which this package must not import (`walk.ts` says why the edge only points
 * the other way).
 *
 * Membership is TRANSITIVE: a subsystem's view includes every service beneath
 * it at any depth, so a parent's view is the whole group's map rather than an
 * empty frame around its children. An empty view body is legal LikeC4 (same
 * spike), so an empty subsystem renders as one — `subsystem new` must be
 * usable before anything moves in.
 *
 * Include lines name the landscape ELEMENT id, resolved through the same
 * element→service join `validate` uses (`serviceResolver`: explicit
 * `metadata { service }` binding first, then a title naming a real service) —
 * because element ids in real landscapes are not service ids, and a view of
 * raw service ids would silently render empty for every such fleet. A member
 * with no landscape element is omitted from the includes: the omission is
 * already an error (`landscape.service-unmodelled`), and rendering only what
 * the committed landscape resolves keeps the output a function of committed
 * bytes alone.
 */
import { type Elem } from "../../c4/likec4.js";
import { serviceResolver } from "../../c4/resolve/service.js";
import { servicesUnder } from "./find.js";
import type { FleetTree, SubsystemEntry, WalkedService } from "./walk.js";

/**
 * The header every generated file opens with — stable bytes, part of the
 * byte-compare contract, naming the regenerator so a reader who found the
 * file first knows what owns it.
 */
const HEADER =
  "// generated by loam — the subsystem tree under services/, one view per subsystem.\n" +
  "// Do not edit: `loam subsystem sync` regenerates this file from the directories,\n" +
  "// and `loam validate --all` reports `subsystem.views-stale` when it drifts.\n";

/**
 * Render the views file for a walked tree, or null when the tree has no
 * subsystems — the file must then be ABSENT, so a flat fleet never carries a
 * generated artifact that says nothing.
 */
export function renderSubsystemViews(tree: FleetTree, elements: Elem[]): string | null {
  if (tree.subsystems.length === 0) return null;
  const elementOf = elementByService(tree, elements);
  const lines: string[] = [HEADER, "views {"];
  const subsystems = [...tree.subsystems].sort((a, b) => (pathKey(a) < pathKey(b) ? -1 : 1));
  for (const [i, sub] of subsystems.entries()) {
    if (i > 0) lines.push("");
    lines.push(`  // services/${pathKey(sub)}`);
    lines.push(`  view ${subsystemViewId(sub)} {`);
    for (const member of membersOf(tree, sub)) {
      const element = elementOf.get(member.id);
      if (element !== undefined) lines.push(`    include ${element}`);
    }
    lines.push("  }");
  }
  lines.push("}");
  return lines.join("\n") + "\n";
}

/**
 * The landscape element standing for each service id: for every element,
 * resolve it through the shared join, and let the SHALLOWEST element win
 * (document order breaking ties). Shallowest, because `serviceResolver`
 * resolves a service's own containers to the service too, and a view should
 * include the service-level box, not whichever nested container happened to
 * be declared first.
 */
function elementByService(tree: FleetTree, elements: Elem[]): Map<string, string> {
  const known: ReadonlySet<string> = new Set(tree.services.map((s) => s.id));
  const resolve = serviceResolver(elements, known);
  const depth = (id: string): number => id.split(".").length;
  const out = new Map<string, string>();
  for (const e of elements) {
    const service = resolve(e.id);
    if (!known.has(service)) continue;
    const held = out.get(service);
    if (held === undefined || depth(e.id) < depth(held)) out.set(service, e.id);
  }
  return out;
}

/** Services beneath this subsystem at any depth, ordered by id — the transitive membership. */
function membersOf(tree: FleetTree, sub: SubsystemEntry): WalkedService[] {
  return [...servicesUnder(tree, sub)].sort((a, b) => (a.id < b.id ? -1 : 1));
}

/** The sort key and the comment spelling: the subsystem's path from services/, joined. */
function pathKey(sub: SubsystemEntry): string {
  return sub.path.join("/");
}

/**
 * A LikeC4 identifier for the view, derived from the subsystem's path so
 * nesting reads in the name — and INJECTIVE over every path the name grammar
 * admits, because the renderer refuses the whole `architecture/` project over
 * a duplicate view id. The naive folding (every non-identifier byte and the
 * join separator alike becoming `_`) collided three DISTINCT healthy names
 * onto one identifier — `a_b`, and `b` under `a`, both rendered
 * `subsystem_a_b` — so `validate --all` was green while the renderer refused
 * the fleet map; `subsystem.name-collision` never fires because the flat
 * namespace really is intact. Hence the encoding: an identifier byte
 * (`[A-Za-z0-9]`) passes through, any other byte becomes `_` + two lowercase
 * hex digits (`.` → `_2e`, `-` → `_2d`, `_` itself → `_5f` — the underscore
 * must be escaped precisely because it is BOTH legal in a name and the
 * separator), and segments join on `__`. Underscore runs then decode
 * uniquely — one is an escape, two a separator, three a separator followed
 * by an escape — so no two distinct legal paths share an identifier. A name
 * `subsystem.name-invalid` already flagged may hold a code point above 0xff
 * whose longer hex could in principle re-collide; it is deterministic still,
 * and that directory is already an error finding by name.
 *
 * EXPORTED, with its prefix, because `subsystem.view-id-collision` has to ask
 * the generator what it mints rather than re-deriving it. A check carrying its
 * own copy of the escaping above would go quiet the day the encoding changed,
 * and going quiet is the failure this whole family exists to prevent.
 */
export const SUBSYSTEM_VIEW_PREFIX = "subsystem_";

export function subsystemViewId(sub: SubsystemEntry): string {
  const segment = (name: string): string =>
    [...name].map((ch) => (/[A-Za-z0-9]/.test(ch) ? ch : `_${ch.codePointAt(0)!.toString(16).padStart(2, "0")}`)).join("");
  return `subsystem_${sub.path.map(segment).join("__")}`;
}
