/**
 * The Gherkin emission: spec scenarios become real `.feature` files.
 *
 * Scenarios have been "the source for tests" since SCHEMA.md's first draft, but
 * until now they only left the docs repo as projected markdown — prose a coding
 * agent could paraphrase into something easier to pass. The emission closes the
 * gap mechanically: one `.feature` file per requirement, steps taken from the
 * scenario's own bullet lines, and a digest TAG (`@loam-digest-<16hex>`) on
 * every scenario using the SAME body-hash recipe `loam verify` folds into its
 * claim ids (`verify/checklist.ts`'s scenarioBodyHash — salted by the owning service and
 * by the spec axis, so a stamp belongs to one suite and one axis) — so the
 * test skeleton, the claim and the spec can never quietly disagree about what
 * a scenario says, and no two repositories can answer each other's. A tag
 * rather than a comment because tags are what cucumber's JSON report carries
 * per scenario: the stamp rides through the runner untouched, which is what
 * lets `loam verify --results` match a report scenario back to its claim.
 *
 * The files land in the SERVICE repo — the docs repo states the questions, the
 * tests live with the code — under `<gherkinDir>/loam/`. That `loam/`
 * subdirectory is loam's own derived space: regeneration rewrites its scope and
 * removes its orphans, and loam never writes or deletes a byte outside it.
 * Everything here is deterministic on purpose: the same specs yield the same
 * bytes, which is what lets `loam validate` grade staleness by digest instead
 * of by guesswork.
 */
import { join } from "node:path";
import { scenarioBodyHash, type ScenarioAxis } from "../verify/checklist.js";
import { resolveInside } from "../kernel/path-safety.js";

/** Where Gherkin lives in a service repo when loam.json does not say. */
const DEFAULT_GHERKIN_DIR = "features";

/** The subdirectory loam owns outright. Everything loam writes stays inside it. */
const GHERKIN_SUBDIR = "loam";

/** How much of the scenario body hash goes into a `@loam-digest-…` tag. */
export const GHERKIN_DIGEST_LENGTH = 16;

/** The one directory `loam gherkin` may touch: `<repo>/<gherkinDir>/loam/`. */
export function gherkinRoot(repoDir: string, gherkinDir?: string): string {
  return resolveInside(
    repoDir,
    join(gherkinDir ?? DEFAULT_GHERKIN_DIR, GHERKIN_SUBDIR),
    "gherkin output directory",
  );
}

/**
 * The digest stamped onto every generated scenario: verify's scenario body
 * hash, at the sources-digest length. Content identity WITHIN one service and
 * one axis, not provenance — two identically-worded scenarios of one service's
 * one axis share a digest, and that is the point: the stamp answers "does this
 * suite still contain a test for THESE words".
 *
 * Both salts ride in the hash (see `scenarioBodyHash`), so the namespaces stay
 * separate all the way into a cucumber report: a business run can never answer
 * for an arch scenario, and one service's green run can never answer another
 * service's claim just because the two specs spell the sentence the same way.
 * `service` is required and never defaulted — a stamp that forgot it would be
 * a tag no claim matches, and the fleet bug it exists to close would come back
 * silently.
 */
export function scenarioDigest(
  service: string,
  lines: string[],
  axis: ScenarioAxis = "business",
): string {
  return scenarioBodyHash(service, lines, axis).slice(0, GHERKIN_DIGEST_LENGTH);
}

/** The digest as the tag on the line above each `Scenario:`. */
export function scenarioDigestTag(digest: string): string {
  return `@loam-digest-${digest}`;
}

/**
 * A tag token carrying a scenario digest — in a generated file, or in a
 * cucumber JSON report. The leading `@` is optional because some runners
 * (behave) strip it from the tags they report.
 */
export const DIGEST_TAG_RE = /^@?loam-digest-([0-9a-f]{16})$/;

/**
 * Line 1 of every generated file — the AGENTS.md stamp pattern, in Gherkin
 * comment syntax. The version records which loam wrote the file; the rest is
 * the ownership rule in the reader's face, because `loam/` files are rewritten
 * wholesale on regeneration and a hand edit would be silently destroyed.
 */
export function gherkinStampLine(version: string): string {
  return `# generated by loam v${version} — \`loam gherkin\`; do not hand-edit, regenerate instead`;
}

export const STAMP_RE = /^#\s*generated by loam v(\S+)/;

