/**
 * The AGENTS.md version stamp: detection, never refresh.
 *
 * AGENTS.md is written once by `loam init` and never touched again — that is
 * the ownership contract (agent.ts): it is a starting point, and a team's edits
 * to it outrank ours. But the file tells agents to branch on flag and code
 * tables, and those tables describe the binary that wrote them. OpenSpec hit
 * the same wall and answered with auto-refresh, which teaches everyone the file
 * belongs to the tool after all; loam answers with the smallest honest thing —
 * a version stamp in the generated file, and one warning when the stamp is
 * missing or trails the running binary. Reviewing the file and bumping the
 * stamp is a human act, and a hand-curated file silences the warning the same
 * way: by saying, in the stamp, that someone has looked.
 */
import type { Finding } from "../vocabulary/report.js";

/** The stamp `loam init` writes at the top of AGENTS.md. */
export function agentsStampLine(version: string): string {
  return `<!-- generated by loam v${version} -->`;
}

/** Matches a stamp line anywhere in the file; the capture is the version text. */
const STAMP_RE = /<!--\s*generated by loam v(\S+?)\s*-->/;

/**
 * The version the stamp names, or null when there is no stamp (or one whose
 * version does not read as numbers — unparseable is indistinguishable from
 * absent, and both get the same advice).
 */
export function agentsStampVersion(text: string): string | null {
  const m = STAMP_RE.exec(text);
  return m !== null && parseVersion(m[1]!) !== null ? m[1]! : null;
}

/** A version split the way precedence is decided: the triple, then the prerelease identifiers. */
interface ParsedVersion {
  release: [number, number, number];
  /**
   * The dot-separated identifiers of a `-beta.2` suffix, empty for a final
   * release. Build metadata (`+sha`) is dropped — semver excludes it from
   * precedence, and two builds of one version are the same instructions.
   */
  pre: string[];
}

/** `X.Y.Z[-pre][+build]`, or null when the leading triple does not read as numbers. */
function parseVersion(v: string): ParsedVersion | null {
  const m = /^(\d+)\.(\d+)\.(\d+)(?:-([0-9A-Za-z.-]+))?(?:\+[0-9A-Za-z.-]+)?$/.exec(v);
  if (m === null) return null;
  return {
    release: [Number(m[1]), Number(m[2]), Number(m[3])],
    pre: m[4] === undefined ? [] : m[4].split("."),
  };
}

/**
 * Semver identifier precedence: numeric identifiers compare numerically and
 * rank below alphanumeric ones, and a longer identifier list outranks a prefix
 * of itself. -1 / 0 / 1, so the caller reads like the triple comparison above.
 */
function comparePre(a: string[], b: string[]): number {
  // No prerelease outranks any prerelease — `1.2.0` is newer than `1.2.0-beta.9`
  // — which is why this cannot be the plain lexicographic walk the identifiers get.
  if (a.length === 0 || b.length === 0) return a.length === b.length ? 0 : a.length === 0 ? 1 : -1;
  for (let i = 0; i < Math.min(a.length, b.length); i += 1) {
    const [x, y] = [a[i]!, b[i]!];
    if (x === y) continue;
    const [nx, ny] = [/^\d+$/.test(x), /^\d+$/.test(y)];
    if (nx && ny) return Number(x) < Number(y) ? -1 : 1;
    if (nx !== ny) return nx ? -1 : 1;
    return x < y ? -1 : 1;
  }
  return a.length === b.length ? 0 : a.length < b.length ? -1 : 1;
}

/**
 * Does `stamp` name an older version than `binary`? A stamp NEWER than the
 * binary does not trail: that is an old binary, not a stale file, and the fix
 * (upgrade loam) is not an AGENTS.md edit.
 *
 * Prerelease identifiers are compared, not ignored, and the difference is the
 * whole reason this check exists. Comparing the numeric triple alone made
 * `0.1.0-beta.1` and `0.1.0-beta.2` indistinguishable — and beta.2 is precisely
 * the release that changed the FORM of every generated file (embedded protocol
 * text became a pointer at `loam instructions`), with a CHANGELOG telling
 * readers to delete the files and re-run `loam init`. The one upgrade that most
 * needed the warning was the one bump shape that could not raise it. A
 * prerelease line is where a generated file's form actually moves, because that
 * is what a prerelease is for.
 */
export function versionTrails(stamp: string, binary: string): boolean {
  const s = parseVersion(stamp);
  const b = parseVersion(binary);
  if (s === null || b === null) return false;
  for (let i = 0; i < 3; i += 1) {
    if (s.release[i]! !== b.release[i]!) return s.release[i]! < b.release[i]!;
  }
  return comparePre(s.pre, b.pre) < 0;
}

/**
 * Does `stamp` name a version NEWER than the binary reading it? The mirror of
 * {@link versionTrails}, and a different subject rather than its negation:
 * equal versions are neither.
 */
export function versionAhead(stamp: string, binary: string): boolean {
  return versionTrails(binary, stamp);
}

/**
 * `docs.binary-behind` — this loam is OLDER than the loam that wrote the docs
 * repo it is reading.
 *
 * The false-green this closes is the sharpest one in the product, because it
 * inverts the meaning of a passing run rather than merely missing a defect.
 * loam's whole promise is that a token spelled here must be spelled there — so
 * every check is an existence constraint over a value the parser recognised.
 * A binary that predates a grammar addition does not FAIL on the newer
 * directive; it does not see it, produces no value, has nothing to join, and
 * reports green. The corpus is checked less than it looks, and nothing anywhere
 * says so. `agents.stale` is the opposite direction and explicitly declines
 * this case ("that is an old binary, not a stale file") — correctly, because
 * the fix is different: upgrade loam, do not edit the file.
 *
 * A WARNING, not an error, and the reasoning is the `sources.stale` doctrine.
 * A mixed-version fleet is ordinary — one engineer's global install trails a
 * release by a week — and failing every command in that repo would be a
 * refusal aimed at the wrong person on the wrong day. What the message must do
 * instead is say plainly that a green run from this binary is worth less than
 * it appears, which no other finding says. A fleet that wants it to gate has
 * `--strict`, which is exactly the lever that doctrine reserves for this.
 *
 * Silent when there is no file, no stamp, or the stamp is equal or older —
 * every one of those is somebody else's finding.
 */
export function binaryBehindFinding(text: string | null, binary: string): Finding | null {
  if (text === null) return null;
  const stamp = agentsStampVersion(text);
  if (stamp === null || !versionAhead(stamp, binary)) return null;
  return {
    severity: "warn",
    code: "docs.binary-behind",
    message:
      `This docs repo was written by loam v${stamp}; this binary is v${binary}. A newer loam may check ` +
      "joins this one cannot parse — an unrecognised directive is read as prose, so it produces no " +
      "join to fail and this run reports green without having graded it. Treat a pass from this " +
      `binary as incomplete rather than clean, and upgrade to v${stamp} or later (\`npm i -g @ybotok/loam\`). ` +
      "Nothing here is wrong with the documents; the reader is behind them.",
  };
}

/**
 * The one finding `loam validate --all` owes the agent contract. `text` is the
 * docs repo's AGENTS.md, or null when there is none — no file means no contract
 * to have drifted, and this check stays silent rather than inventing a second
 * meaning for its code. Returns null when the stamp is current (or newer).
 */
export function agentsStaleFinding(text: string | null, binary: string): Finding | null {
  if (text === null) return null;
  const stamp = agentsStampVersion(text);
  if (stamp === null) {
    return {
      severity: "warn",
      code: "agents.stale",
      message:
        "AGENTS.md has no version stamp — it predates stamping or was hand-created, so nothing says " +
        "which loam its flag and code tables describe. Review it against the current `loam --help`, " +
        `then add \`${agentsStampLine(binary)}\` near the top; a hand-curated file keeps the warning ` +
        "off the same way, by keeping the stamp current.",
    };
  }
  if (!versionTrails(stamp, binary)) return null;
  return {
    severity: "warn",
    code: "agents.stale",
    message:
      `AGENTS.md was written by loam v${stamp}; this binary is v${binary} — the flag and code tables ` +
      "agents branch on may have moved. Review the file against the current `loam --help`, then " +
      `update the stamp line to v${binary} (a hand-curated file silences this by bumping the stamp itself).`,
  };
}
