/**
 * The AGENTS.md version stamp: detection, never refresh.
 *
 * AGENTS.md is written once by `loam init` and never touched again — that is
 * the ownership contract (agent.ts): it is a starting point, and a team's edits
 * to it outrank ours. But the file tells agents to branch on flag and code
 * tables, and those tables describe the binary that wrote them. OpenSpec hit
 * the same wall and answered with auto-refresh, which teaches everyone the file
 * belongs to the tool after all; loam answers with the smallest honest thing —
 * a version stamp in the generated file, and one warning when the stamp is
 * missing or trails the running binary. Reviewing the file and bumping the
 * stamp is a human act, and a hand-curated file silences the warning the same
 * way: by saying, in the stamp, that someone has looked.
 */
import type { Finding } from "./report.js";

/** The stamp `loam init` writes at the top of AGENTS.md. */
export function agentsStampLine(version: string): string {
  return `<!-- generated by loam v${version} -->`;
}

/** Matches a stamp line anywhere in the file; the capture is the version text. */
const STAMP_RE = /<!--\s*generated by loam v(\S+?)\s*-->/;

/**
 * The version the stamp names, or null when there is no stamp (or one whose
 * version does not read as numbers — unparseable is indistinguishable from
 * absent, and both get the same advice).
 */
export function agentsStampVersion(text: string): string | null {
  const m = STAMP_RE.exec(text);
  return m !== null && parseVersion(m[1]!) !== null ? m[1]! : null;
}

/** The leading numeric triple of `X.Y.Z[-anything]`, or null. */
function parseVersion(v: string): [number, number, number] | null {
  const m = /^(\d+)\.(\d+)\.(\d+)(?:[-+]|$)/.exec(v);
  return m === null ? null : [Number(m[1]), Number(m[2]), Number(m[3])];
}

/**
 * Does `stamp` name an older version than `binary`? Numeric triples only — a
 * prerelease suffix is ignored, so `1.2.0-beta` neither trails nor outranks
 * `1.2.0`. A stamp NEWER than the binary does not trail either: that is an old
 * binary, not a stale file, and the fix (upgrade loam) is not an AGENTS.md edit.
 */
export function versionTrails(stamp: string, binary: string): boolean {
  const s = parseVersion(stamp);
  const b = parseVersion(binary);
  if (s === null || b === null) return false;
  for (let i = 0; i < 3; i += 1) {
    if (s[i]! !== b[i]!) return s[i]! < b[i]!;
  }
  return false;
}

/**
 * The one finding `loam validate --all` owes the agent contract. `text` is the
 * docs repo's AGENTS.md, or null when there is none — no file means no contract
 * to have drifted, and this check stays silent rather than inventing a second
 * meaning for its code. Returns null when the stamp is current (or newer).
 */
export function agentsStaleFinding(text: string | null, binary: string): Finding | null {
  if (text === null) return null;
  const stamp = agentsStampVersion(text);
  if (stamp === null) {
    return {
      severity: "warn",
      code: "agents.stale",
      message:
        "AGENTS.md has no version stamp — it predates stamping or was hand-created, so nothing says " +
        "which loam its flag and code tables describe. Review it against the current `loam --help`, " +
        `then add \`${agentsStampLine(binary)}\` near the top; a hand-curated file keeps the warning ` +
        "off the same way, by keeping the stamp current.",
    };
  }
  if (!versionTrails(stamp, binary)) return null;
  return {
    severity: "warn",
    code: "agents.stale",
    message:
      `AGENTS.md was written by loam v${stamp}; this binary is v${binary} — the flag and code tables ` +
      "agents branch on may have moved. Review the file against the current `loam --help`, then " +
      `update the stamp line to v${binary} (a hand-curated file silences this by bumping the stamp itself).`,
  };
}
