/**
 * The Gherkin emission: spec scenarios become real `.feature` files.
 *
 * Scenarios have been "the source for tests" since SCHEMA.md's first draft, but
 * until now they only left the docs repo as projected markdown — prose a coding
 * agent could paraphrase into something easier to pass. The emission closes the
 * gap mechanically: one `.feature` file per requirement, steps taken from the
 * scenario's own bullet lines, and a digest TAG (`@loam-digest-<16hex>`) on
 * every scenario using the SAME body-hash recipe `loam verify` folds into its
 * claim ids (verify.ts's scenarioBodyHash — salted by the owning service and
 * by the spec axis, so a stamp belongs to one suite and one axis) — so the
 * test skeleton, the claim and the spec can never quietly disagree about what
 * a scenario says, and no two repositories can answer each other's. A tag
 * rather than a comment because tags are what cucumber's JSON report carries
 * per scenario: the stamp rides through the runner untouched, which is what
 * lets `loam verify --results` match a report scenario back to its claim.
 *
 * The files land in the SERVICE repo — the docs repo states the questions, the
 * tests live with the code — under `<gherkinDir>/loam/`. That `loam/`
 * subdirectory is loam's own derived space: regeneration rewrites its scope and
 * removes its orphans, and loam never writes or deletes a byte outside it.
 * Everything here is deterministic on purpose: the same specs yield the same
 * bytes, which is what lets `loam validate` grade staleness by digest instead
 * of by guesswork.
 */
import { existsSync, statSync, type Dirent } from "node:fs";
import { readdir, readFile, realpath } from "node:fs/promises";
import { join, relative, sep } from "node:path";
import { parseRequirements, type Requirement } from "./document/spec.js";
import { scenarioGherkin } from "./vocabulary/steps.js";
import { servicePaths, SPEC_AXES, type SpecAxis } from "./repo/paths.js";
import { listFeatures } from "./repo/repo.js";
import type { FleetContext } from "./fleet-context.js";
import type { Finding } from "./vocabulary/report.js";
import { scenarioBodyHash, type ScenarioAxis } from "./verify.js";
import { resolveInside, UnsafePathError } from "./kernel/path-safety.js";

/** Where Gherkin lives in a service repo when loam.json does not say. */
const DEFAULT_GHERKIN_DIR = "features";

/** The subdirectory loam owns outright. Everything loam writes stays inside it. */
const GHERKIN_SUBDIR = "loam";

/** How much of the scenario body hash goes into a `@loam-digest-…` tag. */
export const GHERKIN_DIGEST_LENGTH = 16;

/** The one directory `loam gherkin` may touch: `<repo>/<gherkinDir>/loam/`. */
export function gherkinRoot(repoDir: string, gherkinDir?: string): string {
  return resolveInside(
    repoDir,
    join(gherkinDir ?? DEFAULT_GHERKIN_DIR, GHERKIN_SUBDIR),
    "gherkin output directory",
  );
}

/**
 * The digest stamped onto every generated scenario: verify's scenario body
 * hash, at the sources-digest length. Content identity WITHIN one service and
 * one axis, not provenance — two identically-worded scenarios of one service's
 * one axis share a digest, and that is the point: the stamp answers "does this
 * suite still contain a test for THESE words".
 *
 * Both salts ride in the hash (see `scenarioBodyHash`), so the namespaces stay
 * separate all the way into a cucumber report: a business run can never answer
 * for an arch scenario, and one service's green run can never answer another
 * service's claim just because the two specs spell the sentence the same way.
 * `service` is required and never defaulted — a stamp that forgot it would be
 * a tag no claim matches, and the fleet bug it exists to close would come back
 * silently.
 */
export function scenarioDigest(
  service: string,
  lines: string[],
  axis: ScenarioAxis = "business",
): string {
  return scenarioBodyHash(service, lines, axis).slice(0, GHERKIN_DIGEST_LENGTH);
}

/** The digest as the tag on the line above each `Scenario:`. */
export function scenarioDigestTag(digest: string): string {
  return `@loam-digest-${digest}`;
}

/**
 * A tag token carrying a scenario digest — in a generated file, or in a
 * cucumber JSON report. The leading `@` is optional because some runners
 * (behave) strip it from the tags they report.
 */
export const DIGEST_TAG_RE = /^@?loam-digest-([0-9a-f]{16})$/;

/**
 * Line 1 of every generated file — the AGENTS.md stamp pattern, in Gherkin
 * comment syntax. The version records which loam wrote the file; the rest is
 * the ownership rule in the reader's face, because `loam/` files are rewritten
 * wholesale on regeneration and a hand edit would be silently destroyed.
 */
export function gherkinStampLine(version: string): string {
  return `# generated by loam v${version} — \`loam gherkin\`; do not hand-edit, regenerate instead`;
}

const STAMP_RE = /^#\s*generated by loam v(\S+)/;

/* ------------------------------------------------------------------ */
/* Emission                                                            */
/* ------------------------------------------------------------------ */

/** The axis label the machine contract speaks. */
export function axisLabel(axis: SpecAxis): "business" | "arch" {
  return axis.key === "archSpec" ? "arch" : "business";
}

/**
 * A requirement name as a file name: lowercase, every non-letter/digit run one
 * hyphen, edges trimmed.
 *
 * The keep-set is `\p{L}\p{N}`, not `[a-z0-9]`, because an ASCII-only slug is
 * not a slug of a non-Latin fleet — it is the empty string. Every requirement
 * written in Chinese, Japanese, Korean, Greek, Cyrillic or Hebrew slugged to
 * nothing, fell back to `requirement`, and the whole service's suite came out
 * as `requirement.feature`, `requirement-2.feature`, … : file names that name
 * nothing, in the one place the mapping is supposed to be legible. So letters
 * of every script survive as themselves.
 *
 * Accents are folded rather than kept, and that is the reason for NFKD first:
 * decomposing splits `é` into `e` + a combining acute, and dropping the
 * combining marks (`\p{M}`) leaves `e`. Without the fold `émojis` and `emojis`
 * would be two files that look identical in a directory listing — and on a
 * filesystem that normalises names (APFS, and HFS+ before it) they would be one
 * file, silently, with the second emission overwriting the first.
 *
 * A name this still leaves empty (all punctuation or emoji) falls back to
 * "requirement" and lets the collision counter number it. Runs collapse to a
 * SINGLE hyphen, which is what keeps the `arch--` prefix an axis marker no
 * business slug can spell.
 */
export function slugOf(name: string): string {
  const s = name
    .normalize("NFKD")
    .replace(/\p{M}+/gu, "")
    .toLowerCase()
    .replace(/[^\p{L}\p{N}]+/gu, "-")
    .replace(/^-+|-+$/g, "");
  return s.length > 0 ? s : "requirement";
}

export interface PlannedFeature {
  /** File name under `<gherkinDir>/loam/` — flat, never a subdirectory. */
  fileName: string;
  axis: SpecAxis;
  requirement: Requirement;
  /** One digest per scenario, in scenario order — what the stamps say. */
  digests: string[];
  /**
   * Names of scenarios that yielded ZERO steps — numbered-step or prose-only
   * legacy bodies. Their `Scenario:` blocks are description-only: cucumber
   * runs them vacuously green, while `--results` (which requires at least one
   * passed step) can never confirm them — so the emission must say so out
   * loud, and the fix is rewording the spec bullets, never editing the file.
   */
  stepless: string[];
  content: string;
}

/**
 * The emission plan for one scope: one `.feature` per requirement.
 *
 * File naming is the mapping's contract, so it is spelled here once:
 * `<slug>.feature` for the business axis, `arch--<slug>.feature` for the
 * architecture axis — flat and diffable, and collision-proof across axes
 * because slugs collapse punctuation runs to a single hyphen, so no business
 * slug can ever begin `arch--`. Two requirements slugging identically are
 * disambiguated in document order: the first keeps the bare slug, later ones
 * take `-2`, `-3`, … (counting up past any name that already owns the suffix).
 *
 * Tags ride the `Feature:` line and are inherited by every scenario in the
 * file: `@<FEAT>` in feature mode (living emissions carry no feature tag),
 * `@architecture` on the arch axis.
 *
 * `opts.service` is the suite's owner and salts every digest stamp — the same
 * service `loam verify` files the matching claims under. Required, not
 * defaulted: an emission that guessed it would stamp tags no claim matches.
 */
export function planEmission(
  byAxis: Array<{ axis: SpecAxis; reqs: Requirement[] }>,
  opts: { service: string; featureTag?: string; version: string },
): PlannedFeature[] {
  const used = new Set<string>();
  const out: PlannedFeature[] = [];
  for (const { axis, reqs } of byAxis) {
    for (const r of reqs) {
      const base = (axis.key === "archSpec" ? "arch--" : "") + slugOf(r.name);
      let fileName = `${base}.feature`;
      for (let n = 2; used.has(fileName); n += 1) fileName = `${base}-${n}.feature`;
      used.add(fileName);
      const tags = [
        ...(opts.featureTag === undefined ? [] : [`@${opts.featureTag}`]),
        ...(axis.key === "archSpec" ? ["@architecture"] : []),
      ];
      const { content, digests, stepless } = renderFeature(
        r,
        tags,
        opts.version,
        opts.service,
        axisLabel(axis),
      );
      out.push({ fileName, axis, requirement: r, digests, stepless, content });
    }
  }
  return out;
}

/**
 * One requirement as one `.feature` file: `Feature:` is the requirement name,
 * its body text (Operations:/Covers: lines included — they are part of what
 * the requirement says) becomes the feature description, and each scenario
 * renders under its `@loam-digest-…` tag — the tag line sits directly above
 * the `Scenario:` keyword, where Gherkin puts scenario-level tags, so the
 * runner attaches it to the scenario and carries it into the JSON report.
 * Deterministic to the byte.
 *
 * `service` is the owner of the suite being written, and it salts every digest
 * — the same service `loam verify` files the matching claims under. The two
 * have to be the same string or the stamps this writes match no claim at all.
 */
export function renderFeature(
  r: Requirement,
  tags: string[],
  version: string,
  service: string,
  axis: ScenarioAxis = "business",
): { content: string; digests: string[]; stepless: string[] } {
  const lines: string[] = [gherkinStampLine(version)];
  if (tags.length > 0) lines.push(tags.join(" "));
  lines.push(`Feature: ${r.name}`);
  const text = r.text.join("\n").trim();
  if (text.length > 0) {
    lines.push("");
    for (const l of text.split("\n")) lines.push(l.length > 0 ? `  ${l}` : "");
  }
  const digests: string[] = [];
  const stepless: string[] = [];
  for (const s of r.scenarios) {
    const digest = scenarioDigest(service, s.lines, axis);
    digests.push(digest);
    lines.push("", `  ${scenarioDigestTag(digest)}`, `  Scenario: ${s.name}`);
    const { description, steps } = scenarioGherkin(s.lines);
    if (steps.length === 0) stepless.push(s.name);
    for (const d of description) lines.push(`    ${d}`);
    for (const st of steps) lines.push(`    ${st}`);
  }
  return { content: lines.join("\n") + "\n", digests, stepless };
}

/* ------------------------------------------------------------------ */
/* Reading generated files back                                        */
/* ------------------------------------------------------------------ */

export interface StampedScenario {
  name: string;
  digest: string;
}

/** A generated file as the staleness checks see it. */
export interface StampedFeature {
  /** The version in the stamp line — which loam wrote the file. */
  version: string;
  /** Tag tokens (without `@`) from tag lines above `Feature:`. */
  tags: string[];
  /** The `Feature:` line's text — the requirement name, by the mapping. */
  featureName: string | null;
  /** Scenarios carrying a `@loam-digest-…` tag. A hand-added scenario has none and is invisible here. */
  scenarios: StampedScenario[];
}

/**
 * Parse a `.feature` file for its loam stamps. Null when line 1 is not the
 * stamp — an unstamped file is not loam's writing, and no staleness judgment
 * may be built on it. Tag lines above `Feature:` are the file's tags; a tag
 * line after it that carries a `@loam-digest-…` token binds that digest to the
 * immediately following `Scenario:` line (tag lines stack, as Gherkin's do,
 * without breaking the bond); any other non-blank line between them breaks it.
 */
export function parseStampedFeature(text: string): StampedFeature | null {
  const lines = text.split(/\r?\n/);
  const m = STAMP_RE.exec(lines[0] ?? "");
  if (!m) return null;
  const tags: string[] = [];
  let featureName: string | null = null;
  const scenarios: StampedScenario[] = [];
  let pending: string | null = null;
  for (const line of lines.slice(1)) {
    if (/^\s*@/.test(line)) {
      for (const t of line.trim().split(/\s+/)) {
        if (featureName === null) {
          if (t.startsWith("@")) tags.push(t.slice(1));
          continue;
        }
        const d = DIGEST_TAG_RE.exec(t);
        if (d) pending = d[1]!;
      }
      continue;
    }
    const f = /^\s*Feature:\s*(.*)$/.exec(line);
    if (f && featureName === null) {
      featureName = f[1]!.trim();
      continue;
    }
    const s = /^\s*Scenario(?: Outline)?:\s*(.*)$/.exec(line);
    if (s) {
      if (pending !== null) scenarios.push({ name: s[1]!.trim(), digest: pending });
      pending = null;
      continue;
    }
    if (pending !== null && line.trim().length > 0) pending = null;
  }
  return { version: m[1]!, tags, featureName, scenarios };
}

/* ------------------------------------------------------------------ */
/* Staleness — what `loam validate` reports about a generated suite    */
/* ------------------------------------------------------------------ */

/**
 * The gherkin freshness chain, service-repo-scoped like `sources.*`: it needs
 * the repo (the suite lives there), and it stays quiet until
 * `<gherkinDir>/loam/` exists — a service that never generated has not opted
 * in, and silence there is honest, not vacuous.
 *
 * The LIVING specs are the reference, with one carve-out. A stamped file
 * tagged with a feature still in flight answers to that feature's delta, not
 * to the living spec its requirements have not merged into yet — so it is
 * skipped here (its regeneration is `loam gherkin <FEAT>`), and the moment the
 * feature archives, its requirements ARE living requirements, digests
 * unchanged, and the same file grades current with no rewrite. A tag naming
 * no active feature (the feature was archived, or abandoned) gets no
 * exemption: the living spec is all there is to answer to.
 *
 * Three warnings, one per way the suite and the spec can disagree, judged
 * digest-first and by requirement name second:
 *
 * - `gherkin.missing` — a living scenario whose digest no stamped scenario of
 *   its axis carries: the suite has no test for these words.
 * - `gherkin.stale` — a stamped scenario whose digest matches no living
 *   scenario while its file's requirement still exists: the spec moved under
 *   the generated file. (A reworded scenario therefore reports both: the old
 *   words are stale, the new words are missing — one regeneration clears
 *   both.)
 * - `gherkin.orphaned` — a whole file whose requirement no longer exists in
 *   its axis's living spec; reported once per file, because every scenario in
 *   it is moot together.
 *
 * Digests are content identity within one service and one axis, deliberately:
 * two identically-worded scenarios of one service's one axis share one digest,
 * so one stamped copy covers both — while the axes stay separate namespaces
 * twice over (every comparison here is axis-scoped, and the recipe salts the
 * arch axis), and the services stay separate because the recipe salts the
 * service too. That last salt is why a stamped file copied out of another
 * service's repository grades `gherkin.orphaned`/`gherkin.stale` here instead
 * of quietly counting as this service's coverage.
 *
 * All warnings — `--strict` is the CI escalation — plus one `ok` confirmation
 * (`gherkin.current`, the `sources.current` pattern) when a generated suite
 * exists and nothing disagrees.
 */
export async function gherkinFindings(ctx: {
  docsDir: string;
  service: string;
  /** The service repo, when loam is standing in it. Undefined disables the chain, like sources.*. */
  repoDir?: string;
  gherkinDir?: string;
  fleet?: FleetContext;
}): Promise<Finding[]> {
  if (ctx.repoDir === undefined) return [];
  let root: string;
  try {
    root = gherkinRoot(ctx.repoDir, ctx.gherkinDir);
  } catch (err) {
    if (!(err instanceof UnsafePathError)) throw err;
    return [
      {
        severity: "error",
        code: "gherkin.path-outside",
        subject: ctx.service,
        message: `The configured Gherkin output is unsafe: ${err.message}. It must stay inside the service repo.`,
      },
    ];
  }
  if (!existsSync(root)) return [];

  // The living reference, per axis: requirement names, and scenario digests.
  interface AxisState {
    file: string;
    reqNames: Set<string>;
    digests: Set<string>;
    scenarios: Array<{ req: string; name: string; digest: string }>;
  }
  const paths = servicePaths(ctx.docsDir, ctx.service);
  const axes = new Map<"business" | "arch", AxisState>();
  for (const axis of SPEC_AXES) {
    const label = axisLabel(axis);
    const state: AxisState = { file: axis.file, reqNames: new Set(), digests: new Set(), scenarios: [] };
    const path = paths[axis.key];
    if (existsSync(path)) {
      const reqs = ctx.fleet === undefined
        ? parseRequirements(await readFile(path, "utf8"))
        : await ctx.fleet.readRequirements(path);
      for (const r of reqs) {
        if (r.kind === "REMOVED") continue;
        state.reqNames.add(r.name);
        for (const s of r.scenarios) {
          const digest = scenarioDigest(ctx.service, s.lines, label);
          state.digests.add(digest);
          state.scenarios.push({ req: r.name, name: s.name, digest });
        }
      }
    }
    axes.set(label, state);
  }

  // The stamped side. Every stamped digest counts toward coverage — an
  // in-flight file whose scenario matches the living words IS a test for them.
  const active = new Set((await listFeatures(ctx.docsDir, {}, ctx.fleet)).map((f) => f.id));
  const stampedDigests = { business: new Set<string>(), arch: new Set<string>() };
  const parsed: Array<{ rel: string; axis: "business" | "arch"; file: StampedFeature }> = [];
  let stampedScenarios = 0;
  for (const abs of await featureFilesUnder(root)) {
    const file = parseStampedFeature(await readFile(abs, "utf8"));
    if (file === null) continue;
    const axis = file.tags.includes("architecture") ? "arch" : "business";
    for (const s of file.scenarios) stampedDigests[axis].add(s.digest);
    stampedScenarios += file.scenarios.length;
    parsed.push({ rel: relative(ctx.repoDir, abs).split(sep).join("/"), axis, file });
  }

  const findings: Finding[] = [];
  const regen = `\`loam gherkin --service ${ctx.service}\``;
  for (const [axis, state] of axes) {
    for (const sc of state.scenarios) {
      if (stampedDigests[axis].has(sc.digest)) continue;
      findings.push({
        severity: "warn",
        code: "gherkin.missing",
        subject: ctx.service,
        message: `${ctx.service}: scenario '${sc.name}' of requirement '${sc.req}' (${state.file}) has no generated .feature scenario — the suite has no test for these words; ${regen} regenerates it`,
      });
    }
  }
  for (const { rel, axis, file } of parsed) {
    if (file.tags.some((t) => active.has(t))) continue;
    const state = axes.get(axis)!;
    if (file.featureName === null || !state.reqNames.has(file.featureName)) {
      findings.push({
        severity: "warn",
        code: "gherkin.orphaned",
        subject: ctx.service,
        message: `${ctx.service}: ${rel}: requirement '${file.featureName ?? "(unnamed)"}' no longer exists in the living ${state.file} — the whole file is orphaned; ${regen} removes it`,
      });
      continue;
    }
    for (const s of file.scenarios) {
      if (state.digests.has(s.digest)) continue;
      findings.push({
        severity: "warn",
        code: "gherkin.stale",
        subject: ctx.service,
        message: `${ctx.service}: ${rel}: scenario '${s.name}' matches no scenario in the living ${state.file} — the spec moved under the generated file; ${regen} regenerates it`,
      });
    }
  }
  if (findings.length === 0) {
    findings.push({
      severity: "ok",
      code: "gherkin.current",
      message: `${ctx.service}: generated gherkin current (${parsed.length} file(s), ${stampedScenarios} stamped scenario(s) agree with the living specs)`,
    });
  }
  return findings;
}

/**
 * Every `.feature` file at or under `root`, sorted by repo-relative path —
 * enumeration is part of the output contract, so the order cannot depend on
 * the filesystem's. Dot-entries are skipped, like every other walk in loam.
 *
 * Symlinks are FOLLOWED — repo.ts's `entryIs` and brief.ts's `hasMarkdown` are
 * the same rule for the same reason. A `Dirent` from `readdir(withFileTypes)`
 * never follows one, so `isFile()` and `isDirectory()` are both false for a
 * symlinked `.feature`: it was invisible to the orphan scan (`loam gherkin`
 * left it behind forever) and invisible to the staleness scan (it graded as no
 * coverage at all). Composing a suite out of links is legitimate, so they are
 * followed rather than refused, and a dangling one is skipped exactly as an
 * absent file is.
 */
export async function featureFilesUnder(root: string): Promise<string[]> {
  const out: string[] = [];
  // Following links means a cycle is now possible; every directory is entered
  // once by its resolved path, so a loop terminates instead of hanging.
  const entered = new Set<string>();
  const walk = async (dir: string): Promise<void> => {
    if (!existsSync(dir)) return;
    let resolved: string;
    try {
      resolved = await realpath(dir);
    } catch {
      return;
    }
    if (entered.has(resolved)) return;
    entered.add(resolved);
    for (const entry of await readdir(dir, { withFileTypes: true })) {
      if (entry.name.startsWith(".")) continue;
      const abs = join(dir, entry.name);
      const what = entryKind(abs, entry);
      if (what === "dir") await walk(abs);
      else if (what === "file" && entry.name.endsWith(".feature")) out.push(abs);
    }
  };
  await walk(root);
  return out.sort((a, b) => {
    const ra = a.split(sep).join("/");
    const rb = b.split(sep).join("/");
    return ra < rb ? -1 : ra > rb ? 1 : 0;
  });
}

/** What an entry IS, resolving a symlink to find out. Nothing when it dangles. */
function entryKind(abs: string, e: Dirent): "dir" | "file" | null {
  if (!e.isSymbolicLink()) return e.isDirectory() ? "dir" : e.isFile() ? "file" : null;
  try {
    const s = statSync(abs);
    return s.isDirectory() ? "dir" : s.isFile() ? "file" : null;
  } catch {
    return null;
  }
}
