/**
 * The Gherkin emission: spec scenarios become real `.feature` files.
 *
 * Scenarios have been "the source for tests" since SCHEMA.md's first draft, but
 * until now they only left the docs repo as projected markdown — prose a coding
 * agent could paraphrase into something easier to pass. The emission closes the
 * gap mechanically: one `.feature` file per requirement, steps taken from the
 * scenario's own bullet lines, and a digest stamped beside every scenario using
 * the SAME body-hash recipe `loam verify` folds into its claim ids
 * (verify.ts's scenarioBodyHash) — so the test skeleton, the claim and the spec
 * can never quietly disagree about what a scenario says.
 *
 * The files land in the SERVICE repo — the docs repo states the questions, the
 * tests live with the code — under `<gherkinDir>/loam/`. That `loam/`
 * subdirectory is loam's own derived space: regeneration rewrites its scope and
 * removes its orphans, and loam never writes or deletes a byte outside it.
 * Everything here is deterministic on purpose: the same specs yield the same
 * bytes, which is what lets `loam validate` grade staleness by digest instead
 * of by guesswork.
 */
import { existsSync } from "node:fs";
import { readdir } from "node:fs/promises";
import { join, resolve, sep } from "node:path";
import type { Requirement } from "./spec.js";
import type { SpecAxis } from "./repo.js";
import { scenarioBodyHash } from "./verify.js";

/** Where Gherkin lives in a service repo when loam.json does not say. */
export const DEFAULT_GHERKIN_DIR = "features";

/** The subdirectory loam owns outright. Everything loam writes stays inside it. */
export const GHERKIN_SUBDIR = "loam";

/** How much of the scenario body hash goes into a `# loam:digest` stamp. */
export const GHERKIN_DIGEST_LENGTH = 16;

/** The one directory `loam gherkin` may touch: `<repo>/<gherkinDir>/loam/`. */
export function gherkinRoot(repoDir: string, gherkinDir?: string): string {
  return join(resolve(repoDir, gherkinDir ?? DEFAULT_GHERKIN_DIR), GHERKIN_SUBDIR);
}

/**
 * The digest stamped beside every generated scenario: verify's scenario body
 * hash, at the sources-digest length. Content identity, not provenance — two
 * identically-worded scenarios share a digest, and that is the point: the stamp
 * answers "does the suite still contain a test for THESE words".
 */
export function scenarioDigest(lines: string[]): string {
  return scenarioBodyHash(lines).slice(0, GHERKIN_DIGEST_LENGTH);
}

/**
 * Line 1 of every generated file — the AGENTS.md stamp pattern, in Gherkin
 * comment syntax. The version records which loam wrote the file; the rest is
 * the ownership rule in the reader's face, because `loam/` files are rewritten
 * wholesale on regeneration and a hand edit would be silently destroyed.
 */
export function gherkinStampLine(version: string): string {
  return `# generated by loam v${version} — \`loam gherkin\`; do not hand-edit, regenerate instead`;
}

const STAMP_RE = /^#\s*generated by loam v(\S+)/;
const DIGEST_RE = /^\s*#\s*loam:digest\s+([0-9a-f]{16})\s*$/;

/* ------------------------------------------------------------------ */
/* Step conversion                                                     */
/* ------------------------------------------------------------------ */

const STEP_KEYWORD_RE = /^(given|when|then|and|but)$/i;

export interface Step {
  /** Canonical Gherkin keyword: Given / When / Then / And / But. */
  keyword: string;
  /** The rest of the line, trimmed. May be empty. */
  text: string;
}

/**
 * Is this scenario body line a step? A step is a LIST BULLET (`-`, `*`, `+`)
 * whose text opens with Given/When/Then/And/But — case-insensitive, so the
 * OpenSpec `- **WHEN** ...` convention counts — where the keyword may be
 * wrapped in `**bold**` and may carry a trailing colon. The keyword must stand
 * alone before the step text (`- Givenx` is prose). Everything that is not a
 * step stays scenario description: prose is never dropped, only steps are
 * promoted.
 */
export function stepFromLine(line: string): Step | null {
  const bullet = /^\s*[-*+]\s+(.*)$/.exec(line);
  if (!bullet) return null;
  const rest = bullet[1]!;
  const bold = /^\*\*([^*]+?)\*\*\s*(.*)$/.exec(rest);
  let lead: string;
  let tail: string;
  if (bold) {
    lead = bold[1]!.trim();
    tail = bold[2]!;
  } else {
    const sp = /^(\S+)\s*(.*)$/.exec(rest);
    if (!sp) return null;
    lead = sp[1]!;
    tail = sp[2]!;
  }
  const kw = STEP_KEYWORD_RE.exec(lead.replace(/:$/, ""));
  if (!kw) return null;
  const word = kw[1]!.toLowerCase();
  return { keyword: word[0]!.toUpperCase() + word.slice(1), text: tail.trim() };
}

/**
 * A scenario body split for rendering: bullet lines that read as steps become
 * steps, every other non-blank line is kept (edge-trimmed) as the scenario's
 * description. Description renders BEFORE the steps whatever the source order —
 * Gherkin's grammar ends a description at the first step keyword — so prose
 * survives verbatim but interleaving does not.
 */
export function scenarioGherkin(lines: string[]): { description: string[]; steps: string[] } {
  const description: string[] = [];
  const steps: string[] = [];
  for (const line of lines) {
    if (line.trim().length === 0) continue;
    const step = stepFromLine(line);
    if (step) steps.push(step.text.length > 0 ? `${step.keyword} ${step.text}` : step.keyword);
    else description.push(line.trim());
  }
  return { description, steps };
}

/* ------------------------------------------------------------------ */
/* Emission                                                            */
/* ------------------------------------------------------------------ */

/** The axis label the machine contract speaks. */
export function axisLabel(axis: SpecAxis): "business" | "arch" {
  return axis.key === "archSpec" ? "arch" : "business";
}

/**
 * A requirement name as a file name: lowercase, every non-alphanumeric run one
 * hyphen, edges trimmed. A name this leaves empty (all punctuation, non-Latin)
 * falls back to "requirement" and lets the collision counter number it.
 */
export function slugOf(name: string): string {
  const s = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return s.length > 0 ? s : "requirement";
}

export interface PlannedFeature {
  /** File name under `<gherkinDir>/loam/` — flat, never a subdirectory. */
  fileName: string;
  axis: SpecAxis;
  requirement: Requirement;
  /** One digest per scenario, in scenario order — what the stamps say. */
  digests: string[];
  content: string;
}

/**
 * The emission plan for one scope: one `.feature` per requirement.
 *
 * File naming is the mapping's contract, so it is spelled here once:
 * `<slug>.feature` for the business axis, `arch--<slug>.feature` for the
 * architecture axis — flat and diffable, and collision-proof across axes
 * because slugs collapse punctuation runs to a single hyphen, so no business
 * slug can ever begin `arch--`. Two requirements slugging identically are
 * disambiguated in document order: the first keeps the bare slug, later ones
 * take `-2`, `-3`, … (counting up past any name that already owns the suffix).
 *
 * Tags ride the `Feature:` line and are inherited by every scenario in the
 * file: `@<FEAT>` in feature mode (living emissions carry no feature tag),
 * `@architecture` on the arch axis.
 */
export function planEmission(
  byAxis: Array<{ axis: SpecAxis; reqs: Requirement[] }>,
  opts: { featureTag?: string; version: string },
): PlannedFeature[] {
  const used = new Set<string>();
  const out: PlannedFeature[] = [];
  for (const { axis, reqs } of byAxis) {
    for (const r of reqs) {
      const base = (axis.key === "archSpec" ? "arch--" : "") + slugOf(r.name);
      let fileName = `${base}.feature`;
      for (let n = 2; used.has(fileName); n += 1) fileName = `${base}-${n}.feature`;
      used.add(fileName);
      const tags = [
        ...(opts.featureTag === undefined ? [] : [`@${opts.featureTag}`]),
        ...(axis.key === "archSpec" ? ["@architecture"] : []),
      ];
      const { content, digests } = renderFeature(r, tags, opts.version);
      out.push({ fileName, axis, requirement: r, digests, content });
    }
  }
  return out;
}

/**
 * One requirement as one `.feature` file: `Feature:` is the requirement name,
 * its body text (Operations:/Covers: lines included — they are part of what
 * the requirement says) becomes the feature description, and each scenario
 * renders under its `# loam:digest` stamp. Deterministic to the byte.
 */
export function renderFeature(
  r: Requirement,
  tags: string[],
  version: string,
): { content: string; digests: string[] } {
  const lines: string[] = [gherkinStampLine(version)];
  if (tags.length > 0) lines.push(tags.join(" "));
  lines.push(`Feature: ${r.name}`);
  const text = r.text.join("\n").trim();
  if (text.length > 0) {
    lines.push("");
    for (const l of text.split("\n")) lines.push(l.length > 0 ? `  ${l}` : "");
  }
  const digests: string[] = [];
  for (const s of r.scenarios) {
    const digest = scenarioDigest(s.lines);
    digests.push(digest);
    lines.push("", `  # loam:digest ${digest}`, `  Scenario: ${s.name}`);
    const { description, steps } = scenarioGherkin(s.lines);
    for (const d of description) lines.push(`    ${d}`);
    for (const st of steps) lines.push(`    ${st}`);
  }
  return { content: lines.join("\n") + "\n", digests };
}

/* ------------------------------------------------------------------ */
/* Reading generated files back                                        */
/* ------------------------------------------------------------------ */

export interface StampedScenario {
  name: string;
  digest: string;
}

/** A generated file as the staleness checks see it. */
export interface StampedFeature {
  /** The version in the stamp line — which loam wrote the file. */
  version: string;
  /** Tag tokens (without `@`) from tag lines above `Feature:`. */
  tags: string[];
  /** The `Feature:` line's text — the requirement name, by the mapping. */
  featureName: string | null;
  /** Scenarios carrying a `# loam:digest` stamp. A hand-added scenario has none and is invisible here. */
  scenarios: StampedScenario[];
}

/**
 * Parse a `.feature` file for its loam stamps. Null when line 1 is not the
 * stamp — an unstamped file is not loam's writing, and no staleness judgment
 * may be built on it. A digest comment binds to the immediately following
 * `Scenario:` line; any other non-blank line between them breaks the bond.
 */
export function parseStampedFeature(text: string): StampedFeature | null {
  const lines = text.split(/\r?\n/);
  const m = STAMP_RE.exec(lines[0] ?? "");
  if (!m) return null;
  const tags: string[] = [];
  let featureName: string | null = null;
  const scenarios: StampedScenario[] = [];
  let pending: string | null = null;
  for (const line of lines.slice(1)) {
    if (featureName === null && /^\s*@/.test(line)) {
      for (const t of line.trim().split(/\s+/)) if (t.startsWith("@")) tags.push(t.slice(1));
      continue;
    }
    const f = /^\s*Feature:\s*(.*)$/.exec(line);
    if (f && featureName === null) {
      featureName = f[1]!.trim();
      continue;
    }
    const d = DIGEST_RE.exec(line);
    if (d) {
      pending = d[1]!;
      continue;
    }
    const s = /^\s*Scenario(?: Outline)?:\s*(.*)$/.exec(line);
    if (s) {
      if (pending !== null) scenarios.push({ name: s[1]!.trim(), digest: pending });
      pending = null;
      continue;
    }
    if (pending !== null && line.trim().length > 0) pending = null;
  }
  return { version: m[1]!, tags, featureName, scenarios };
}

/**
 * Every `.feature` file at or under `root`, sorted by repo-relative path —
 * enumeration is part of the output contract, so the order cannot depend on
 * the filesystem's. Dot-entries are skipped, like every other walk in loam.
 */
export async function featureFilesUnder(root: string): Promise<string[]> {
  const out: string[] = [];
  const walk = async (dir: string): Promise<void> => {
    if (!existsSync(dir)) return;
    for (const entry of await readdir(dir, { withFileTypes: true })) {
      if (entry.name.startsWith(".")) continue;
      const abs = join(dir, entry.name);
      if (entry.isDirectory()) await walk(abs);
      else if (entry.isFile() && entry.name.endsWith(".feature")) out.push(abs);
    }
  };
  await walk(root);
  return out.sort((a, b) => {
    const ra = a.split(sep).join("/");
    const rb = b.split(sep).join("/");
    return ra < rb ? -1 : ra > rb ? 1 : 0;
  });
}
