/**
 * The README a new docs repo starts with — the one file in it addressed to a
 * person.
 *
 * Everything else the scaffold lays down is either a document about the
 * governed system or `AGENTS.md`, which is 1500 lines written for a coding
 * agent and named so that a human does not open it. A forge renders `README.md`
 * as the repository's landing page and nothing else, so without this file a
 * docs repo opens as a bare directory listing: four folders and two config
 * files, and no sentence anywhere saying what any of it is.
 *
 * Deliberately SHORT, and deliberately not a second copy of anything. The
 * layout table and the cycle are AGENTS.md's, in full; this page says what the
 * repo is, points at the three commands a person actually types, and hands off.
 * A README that restated the contract would be a second thing to keep true, and
 * the first one to go stale.
 */
export const README_FILENAME = "README.md";

export const README_MD = `# Architecture & specs

This repository is a governed system's **source of truth**: its architecture,
requirements, contracts, domain vocabulary and verification evidence, kept in
explicit agreement. It is plain files — Markdown, YAML and LikeC4 — reviewed like
code, in pull requests.

In paths and commands, loam calls one governed implementation boundary a
**service**. That boundary may be a modular monolith, a network service, a CLI or
a worker. Nested C4 elements remain modules or components unless they need their
own repository binding, contracts, evidence and deployment boundary.

It is read and written with [**loam**](https://github.com/ybotok/loam). Delete
loam and these documents still make sense; that is the point of keeping them this
way.

## What is where

| | |
|---|---|
| \`architecture/landscape.likec4\` | the system map — governed boundaries, nested structure and their relationships |
| \`services/<id>/\` | one directory per governed boundary: what it promises, exposes and verifies |
| \`features/<FEAT>/\` | a change in flight — why it exists, and the delta it makes to the documents above |
| \`features/archive/\` | changes that shipped; their deltas are already merged into the living documents |

A directory under \`services/\` that holds a \`subsystem.yaml\` is a **group**, not
a service — services can be filed inside one at any depth.

## If you are new here

\`\`\`bash
loam status
\`\`\`

It reads the files and tells you where things stand and what to do next, ordered
most-unblocking first, with the exact command for each step. Nothing in this
repository is generated from a database or a server — if \`loam status\` says
something, a file said it first.

To check the whole repository the way CI does:

\`\`\`bash
loam validate --all
\`\`\`

And when a finding's code means nothing to you:

\`\`\`bash
loam explain <code>
\`\`\`

## Changing something

Documents here are edited through a **feature**: \`loam new <FEAT>\` scaffolds one,
you write the intent and the deltas, \`loam validate --feature <FEAT>\` grades it,
and \`loam archive <FEAT>\` merges it into the living documents. Living documents
are not edited directly once a boundary is adopted — the feature is the
reviewable unit, and the archive is what makes the change traceable afterwards.

## For coding agents

\`AGENTS.md\` in this directory is the full contract: the layout in detail, the
authoring rules \`loam validate\` enforces, the ID spine, the cycle, and what every
finding code means. It is generated by loam and kept in step with the binary.
`;
