/**
 * The generated views file: `architecture/flow-groups.likec4`, one LikeC4 view
 * per flow group enumerating the participants its flows touch. GENERATED,
 * never authored — a structural clone of `../repo/tree/views.ts`, and
 * deliberately so: the two files answer the same question about two different
 * groupings, and a second set of rules for determinism, staleness and
 * ownership would be a second set of rules to get wrong.
 *
 * The OWNERSHIP rule is what makes both files safe to keep beside authored
 * ones: within `architecture/`, generated files are loam's and the flow
 * documents under `flows/` are the author's, and neither regenerator touches
 * the other's. `loam flow sync` owns these bytes; `loam subsystem sync` owns
 * `subsystems.likec4`; nothing writes into `architecture/flows/`.
 *
 * The output is deterministic and line-oriented, and both halves are the
 * contract: groups sorted by name, members sorted by id, ONE `include` per
 * line — so two features adding two different journeys to two different suites
 * touch different lines and git merges the file without intervention.
 * Byte-reproducible on any machine: no timestamps, no absolute paths, no
 * readdir-order dependence (the document walk sorts, and every list is
 * re-sorted before it is rendered).
 *
 * Members are the participants' own ELEMENT ids, and no join is needed to say
 * so: a dynamic view's steps name elements the landscape declares, so the ids
 * are already the ones a view may `include`. (The service-level answer — which
 * `services/<id>/` must be up — is a different question with a different
 * consumer, and `./groups.ts` answers it there.) Nothing is filtered out: a
 * participant naming no declared element is a reference LikeC4 itself refuses,
 * so the flows never reach here at all.
 *
 * Staleness is a byte compare, never a parse, for `../repo/tree/views.ts`'s
 * reason: a views-only document does not parse standalone (its `include` lines
 * reference elements the landscape defines), and no check anywhere reads this
 * file's content — the only question loam owes it is "are these the bytes the
 * flows render to".
 */
import { likec4Identifier } from "../kernel/likec4-ident.js";
import type { FlowGroup } from "./groups.js";

/**
 * The header every generated file opens with — stable bytes, part of the
 * byte-compare contract, naming the regenerator so a reader who found the file
 * first knows what owns it.
 */
const HEADER =
  "// generated by loam — the flow groups under architecture/flows/, one view per group.\n" +
  "// Do not edit: `loam flow sync` regenerates this file from the flow documents,\n" +
  "// and `loam validate --all` reports `flow.views-stale` when it drifts.\n";

/**
 * Render the views file for a fleet's groups, or null when no flow declares a
 * group — the file must then be ABSENT, so a fleet that draws journeys without
 * suiting them never carries a generated artifact that says nothing, and a
 * suite deleted months ago does not keep a view forever.
 */
export function renderFlowGroupViews(groups: FlowGroup[]): string | null {
  if (groups.length === 0) return null;
  const lines: string[] = [HEADER, "views {"];
  for (const [i, group] of groups.entries()) {
    if (i > 0) lines.push("");
    // The flow ids in the comment are the group's membership in the file a
    // human opens first: the view body says which BOXES the suite touches, and
    // only this line says which journeys put them there.
    lines.push(`  // group ${group.name} — ${group.flows.join(", ")}`);
    lines.push(`  view ${viewName(group)} {`);
    for (const member of group.members) lines.push(`    include ${member}`);
    lines.push("  }");
  }
  lines.push("}");
  return lines.join("\n") + "\n";
}

/**
 * A LikeC4 identifier for the group's view. The `flow_group_` prefix is this
 * generator's own — keeping each generator's prefix distinct is what stops two
 * of them minting one id for two different things, which the LikeC4 renderer
 * answers by refusing the whole `architecture/` project. The encoding under it
 * is injective (`core/kernel/likec4-ident.ts` records the collision that made
 * it so), so two distinct group tags cannot share a view id either.
 */
function viewName(group: FlowGroup): string {
  return `flow_group_${likec4Identifier([group.name])}`;
}
